// <auto-generated />
#nullable enable
using System.Text.Json;

namespace SumUp;

/// <summary>Sent when a member is created, invited, or accepts an invitation for a merchant account.</summary>
public sealed class MemberCreatedEvent : EventNotification<Member>;

/// <summary>Sent when a member is deleted from a merchant account.</summary>
public sealed class MemberDeletedEvent : EventNotification<Member>;

/// <summary>Sent when a member is updated, disabled, rejected, or expires for a merchant account.</summary>
public sealed class MemberUpdatedEvent : EventNotification<Member>;

/// <summary>Sent when a reader is paired to a merchant account and becomes available through the Readers API.</summary>
public sealed class ReaderCreatedEvent : EventNotification<Reader>;

/// <summary>Sent when a reader is unpaired from a merchant account and is no longer available through the Readers API.</summary>
public sealed class ReaderDeletedEvent : EventNotification<Reader>;

public sealed partial class EventsHandler
{
    /// <summary>Registers a callback for <c>"members.created"</c>, replacing any previous callback for this type.</summary>
    /// <param name="callback">The callback to await, with the request cancellation token.</param>
    /// <returns>This handler, for chaining registrations.</returns>
    public EventsHandler OnMemberCreated(Func<MemberCreatedEvent, CancellationToken, Task> callback) =>
        Register("members.created", callback);

    /// <summary>Registers a callback for <c>"members.deleted"</c>, replacing any previous callback for this type.</summary>
    /// <param name="callback">The callback to await, with the request cancellation token.</param>
    /// <returns>This handler, for chaining registrations.</returns>
    public EventsHandler OnMemberDeleted(Func<MemberDeletedEvent, CancellationToken, Task> callback) =>
        Register("members.deleted", callback);

    /// <summary>Registers a callback for <c>"members.updated"</c>, replacing any previous callback for this type.</summary>
    /// <param name="callback">The callback to await, with the request cancellation token.</param>
    /// <returns>This handler, for chaining registrations.</returns>
    public EventsHandler OnMemberUpdated(Func<MemberUpdatedEvent, CancellationToken, Task> callback) =>
        Register("members.updated", callback);

    /// <summary>Registers a callback for <c>"readers.created"</c>, replacing any previous callback for this type.</summary>
    /// <param name="callback">The callback to await, with the request cancellation token.</param>
    /// <returns>This handler, for chaining registrations.</returns>
    public EventsHandler OnReaderCreated(Func<ReaderCreatedEvent, CancellationToken, Task> callback) =>
        Register("readers.created", callback);

    /// <summary>Registers a callback for <c>"readers.deleted"</c>, replacing any previous callback for this type.</summary>
    /// <param name="callback">The callback to await, with the request cancellation token.</param>
    /// <returns>This handler, for chaining registrations.</returns>
    public EventsHandler OnReaderDeleted(Func<ReaderDeletedEvent, CancellationToken, Task> callback) =>
        Register("readers.deleted", callback);

}

public partial class SumUpClient
{
    private static EventNotification DeserializeEvent(JsonElement root, string? type) => type switch
    {
        "members.created" => root.Deserialize<MemberCreatedEvent>()!,
        "members.deleted" => root.Deserialize<MemberDeletedEvent>()!,
        "members.updated" => root.Deserialize<MemberUpdatedEvent>()!,
        "readers.created" => root.Deserialize<ReaderCreatedEvent>()!,
        "readers.deleted" => root.Deserialize<ReaderDeletedEvent>()!,
        _ => root.Deserialize<EventNotification>()!,
    };
}
