// <auto-generated />
#nullable enable

namespace SumUp;

using System;
using System.Net.Http;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using SumUp.Http;

public sealed partial class MembershipsClient
{
    private readonly ApiClient _client;

    /// <summary>
    /// Client for the Memberships API endpoints.
    /// </summary>
    /// <remarks>Endpoints to manage user's memberships. Memberships are used to connect the user to merchant accounts and to grant them access to the merchant's resources via roles.</remarks>
    internal MembershipsClient(ApiClient client)
    {
        _client = client;
    }

    /// <summary>
    /// List memberships
    /// </summary>
    /// <remarks>List memberships of the current user.</remarks>
    /// <param name="options">Query and header parameters for the request.</param>
    /// <param name="requestOptions">Optional per-request overrides.</param>
    /// <param name="cancellationToken">Token used to cancel the request.</param>
    public ApiResponse<MembershipsListResponse> List(MembershipsListOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        var operationOptions = options ?? new MembershipsListOptions();
        var request = _client.CreateRequest(HttpMethod.Get, "/v0.1/memberships", builder =>
        {
            builder.AddQuery("offset", operationOptions.Offset);
            builder.AddQuery("limit", operationOptions.Limit);
            builder.AddQuery("kind", operationOptions.Kind);
            builder.AddQuery("status", operationOptions.Status);
            builder.AddQuery("resource.type", operationOptions.ResourceType);
            builder.AddQuery("resource.attributes.sandbox", operationOptions.ResourceAttributesSandbox);
            builder.AddQuery("resource.name", operationOptions.ResourceName);
            builder.AddQuery("resource.parent.id", operationOptions.ResourceParentId);
            builder.AddQuery("resource.parent.type", operationOptions.ResourceParentType);
            builder.AddQuery("roles", operationOptions.Roles);
        });
        var effectiveCancellationToken = ApiClient.CreateCancellationToken(cancellationToken, requestOptions, out var timeoutScope);
        try
        {
            _client.ApplyAuthorizationHeaderAsync(request, effectiveCancellationToken, requestOptions).GetAwaiter().GetResult();

            using var response = _client.HttpClient.SendAsync(
                request,
                HttpCompletionOption.ResponseHeadersRead,
                effectiveCancellationToken).GetAwaiter().GetResult();

            if (!response.IsSuccessStatusCode)
            {
                var responseBody = response.Content is null
                    ? null
                    : ApiClient.ReadContentAsStringAsync(response.Content, effectiveCancellationToken).GetAwaiter().GetResult();
                switch ((int)response.StatusCode)
                {
                    case 400:
                    {
                        var errorForStatus400 = _client.TryDeserialize<Problem>(responseBody);
                        throw new ApiException<Problem>(response.StatusCode, errorForStatus400, responseBody, response.RequestMessage?.RequestUri);
                    }
                    case 401:
                    {
                        var errorForStatus401 = _client.TryDeserialize<Problem>(responseBody);
                        throw new ApiException<Problem>(response.StatusCode, errorForStatus401, responseBody, response.RequestMessage?.RequestUri);
                    }
                }
                var fallbackError = _client.TryDeserialize<ApiError>(responseBody);
                throw new ApiException(response.StatusCode, fallbackError, responseBody, response.RequestMessage?.RequestUri);
            }
            using var stream = ApiClient.ReadContentAsStreamAsync(response.Content!, effectiveCancellationToken).GetAwaiter().GetResult();
            var result = JsonSerializer.Deserialize<MembershipsListResponse>(stream, _client.SerializerOptions);
            return ApiResponse<MembershipsListResponse>.From(result, response.StatusCode, response.Headers, response.RequestMessage?.RequestUri);
        }
        finally
        {
            timeoutScope?.Dispose();
        }
    }

    /// <summary>
    /// List memberships
    /// </summary>
    /// <remarks>List memberships of the current user.</remarks>
    /// <param name="options">Query and header parameters for the request.</param>
    /// <param name="requestOptions">Optional per-request overrides.</param>
    /// <param name="cancellationToken">Token used to cancel the request.</param>
    public async Task<ApiResponse<MembershipsListResponse>> ListAsync(MembershipsListOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        var operationOptions = options ?? new MembershipsListOptions();
        var request = _client.CreateRequest(HttpMethod.Get, "/v0.1/memberships", builder =>
        {
            builder.AddQuery("offset", operationOptions.Offset);
            builder.AddQuery("limit", operationOptions.Limit);
            builder.AddQuery("kind", operationOptions.Kind);
            builder.AddQuery("status", operationOptions.Status);
            builder.AddQuery("resource.type", operationOptions.ResourceType);
            builder.AddQuery("resource.attributes.sandbox", operationOptions.ResourceAttributesSandbox);
            builder.AddQuery("resource.name", operationOptions.ResourceName);
            builder.AddQuery("resource.parent.id", operationOptions.ResourceParentId);
            builder.AddQuery("resource.parent.type", operationOptions.ResourceParentType);
            builder.AddQuery("roles", operationOptions.Roles);
        });
        var effectiveCancellationToken = ApiClient.CreateCancellationToken(cancellationToken, requestOptions, out var timeoutScope);
        try
        {
            await _client.ApplyAuthorizationHeaderAsync(request, effectiveCancellationToken, requestOptions).ConfigureAwait(false);

            using var response = await _client.HttpClient.SendAsync(
                request,
                HttpCompletionOption.ResponseHeadersRead,
                effectiveCancellationToken).ConfigureAwait(false);

            if (!response.IsSuccessStatusCode)
            {
                var responseBody = response.Content is null
                    ? null
                    : await ApiClient.ReadContentAsStringAsync(response.Content, effectiveCancellationToken).ConfigureAwait(false);
                switch ((int)response.StatusCode)
                {
                    case 400:
                    {
                        var errorForStatus400 = _client.TryDeserialize<Problem>(responseBody);
                        throw new ApiException<Problem>(response.StatusCode, errorForStatus400, responseBody, response.RequestMessage?.RequestUri);
                    }
                    case 401:
                    {
                        var errorForStatus401 = _client.TryDeserialize<Problem>(responseBody);
                        throw new ApiException<Problem>(response.StatusCode, errorForStatus401, responseBody, response.RequestMessage?.RequestUri);
                    }
                }
                var fallbackError = _client.TryDeserialize<ApiError>(responseBody);
                throw new ApiException(response.StatusCode, fallbackError, responseBody, response.RequestMessage?.RequestUri);
            }
            using var stream = await ApiClient.ReadContentAsStreamAsync(response.Content!, effectiveCancellationToken).ConfigureAwait(false);
            var result = await JsonSerializer.DeserializeAsync<MembershipsListResponse>(stream, _client.SerializerOptions, effectiveCancellationToken).ConfigureAwait(false);
            return ApiResponse<MembershipsListResponse>.From(result, response.StatusCode, response.Headers, response.RequestMessage?.RequestUri);
        }
        finally
        {
            timeoutScope?.Dispose();
        }
    }
}