// <auto-generated />
#nullable enable

namespace SumUp;

using System;
using System.Net.Http;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using SumUp.Http;

public sealed partial class MembersClient
{
    private readonly ApiClient _client;

    internal MembersClient(ApiClient client)
    {
        _client = client;
    }

    /// <summary>
    /// Create a member
    /// </summary>
    /// <remarks>Create a merchant member.</remarks>
    /// <param name="merchantCode">Short unique identifier for the merchant.</param>
    /// <param name="body">Request body payload.</param>
    /// <param name="cancellationToken">Token used to cancel the request.</param>
    public ApiResponse<Member> Create(string merchantCode, MembersCreateRequest body, CancellationToken cancellationToken = default)
    {
        var request = _client.CreateRequest(HttpMethod.Post, "/v0.1/merchants/{merchant_code}/members", builder =>
        {
            builder.AddPath("merchant_code", merchantCode);
        });
        return _client.Send<Member>(request, body, "application/json", cancellationToken);
    }

    /// <summary>
    /// Create a member
    /// </summary>
    /// <remarks>Create a merchant member.</remarks>
    /// <param name="merchantCode">Short unique identifier for the merchant.</param>
    /// <param name="body">Request body payload.</param>
    /// <param name="cancellationToken">Token used to cancel the request.</param>
    public async Task<ApiResponse<Member>> CreateAsync(string merchantCode, MembersCreateRequest body, CancellationToken cancellationToken = default)
    {
        var request = _client.CreateRequest(HttpMethod.Post, "/v0.1/merchants/{merchant_code}/members", builder =>
        {
            builder.AddPath("merchant_code", merchantCode);
        });
        return await _client.SendAsync<Member>(request, body, "application/json", cancellationToken).ConfigureAwait(false);
    }

    /// <summary>
    /// Delete a member
    /// </summary>
    /// <remarks>Deletes a merchant member.</remarks>
    /// <param name="merchantCode">Short unique identifier for the merchant.</param>
    /// <param name="memberId">The ID of the member to retrieve.</param>
    /// <param name="cancellationToken">Token used to cancel the request.</param>
    public ApiResponse<JsonDocument> Delete(string merchantCode, string memberId, CancellationToken cancellationToken = default)
    {
        var request = _client.CreateRequest(HttpMethod.Delete, "/v0.1/merchants/{merchant_code}/members/{member_id}", builder =>
        {
            builder.AddPath("merchant_code", merchantCode);
            builder.AddPath("member_id", memberId);
        });
        return _client.Send<JsonDocument>(request, null, null, cancellationToken);
    }

    /// <summary>
    /// Delete a member
    /// </summary>
    /// <remarks>Deletes a merchant member.</remarks>
    /// <param name="merchantCode">Short unique identifier for the merchant.</param>
    /// <param name="memberId">The ID of the member to retrieve.</param>
    /// <param name="cancellationToken">Token used to cancel the request.</param>
    public async Task<ApiResponse<JsonDocument>> DeleteAsync(string merchantCode, string memberId, CancellationToken cancellationToken = default)
    {
        var request = _client.CreateRequest(HttpMethod.Delete, "/v0.1/merchants/{merchant_code}/members/{member_id}", builder =>
        {
            builder.AddPath("merchant_code", merchantCode);
            builder.AddPath("member_id", memberId);
        });
        return await _client.SendAsync<JsonDocument>(request, null, null, cancellationToken).ConfigureAwait(false);
    }

    /// <summary>
    /// Retrieve a member
    /// </summary>
    /// <remarks>Retrieve a merchant member.</remarks>
    /// <param name="merchantCode">Short unique identifier for the merchant.</param>
    /// <param name="memberId">The ID of the member to retrieve.</param>
    /// <param name="cancellationToken">Token used to cancel the request.</param>
    public ApiResponse<Member> Get(string merchantCode, string memberId, CancellationToken cancellationToken = default)
    {
        var request = _client.CreateRequest(HttpMethod.Get, "/v0.1/merchants/{merchant_code}/members/{member_id}", builder =>
        {
            builder.AddPath("merchant_code", merchantCode);
            builder.AddPath("member_id", memberId);
        });
        return _client.Send<Member>(request, null, null, cancellationToken);
    }

    /// <summary>
    /// Retrieve a member
    /// </summary>
    /// <remarks>Retrieve a merchant member.</remarks>
    /// <param name="merchantCode">Short unique identifier for the merchant.</param>
    /// <param name="memberId">The ID of the member to retrieve.</param>
    /// <param name="cancellationToken">Token used to cancel the request.</param>
    public async Task<ApiResponse<Member>> GetAsync(string merchantCode, string memberId, CancellationToken cancellationToken = default)
    {
        var request = _client.CreateRequest(HttpMethod.Get, "/v0.1/merchants/{merchant_code}/members/{member_id}", builder =>
        {
            builder.AddPath("merchant_code", merchantCode);
            builder.AddPath("member_id", memberId);
        });
        return await _client.SendAsync<Member>(request, null, null, cancellationToken).ConfigureAwait(false);
    }

    /// <summary>
    /// List members
    /// </summary>
    /// <remarks>Lists merchant members.</remarks>
    /// <param name="merchantCode">Short unique identifier for the merchant.</param>
    /// <param name="offset">Offset of the first member to return.</param>
    /// <param name="limit">Maximum number of members to return.</param>
    /// <param name="scroll">Indicates to skip count query.</param>
    /// <param name="email">Filter the returned members by email address prefix.</param>
    /// <param name="userId">Search for a member by user id.</param>
    /// <param name="status">Filter the returned members by the membership status.</param>
    /// <param name="roles">Filter the returned members by role.</param>
    /// <param name="cancellationToken">Token used to cancel the request.</param>
    public ApiResponse<MembersListResponse> List(string merchantCode, int? offset = null, int? limit = null, bool? scroll = null, string? email = null, Guid? userId = null, MembershipStatus? status = null, IEnumerable<string>? roles = null, CancellationToken cancellationToken = default)
    {
        var request = _client.CreateRequest(HttpMethod.Get, "/v0.1/merchants/{merchant_code}/members", builder =>
        {
            builder.AddPath("merchant_code", merchantCode);
            builder.AddQuery("offset", offset);
            builder.AddQuery("limit", limit);
            builder.AddQuery("scroll", scroll);
            builder.AddQuery("email", email);
            builder.AddQuery("user.id", userId);
            builder.AddQuery("status", status);
            builder.AddQuery("roles", roles);
        });
        return _client.Send<MembersListResponse>(request, null, null, cancellationToken);
    }

    /// <summary>
    /// List members
    /// </summary>
    /// <remarks>Lists merchant members.</remarks>
    /// <param name="merchantCode">Short unique identifier for the merchant.</param>
    /// <param name="offset">Offset of the first member to return.</param>
    /// <param name="limit">Maximum number of members to return.</param>
    /// <param name="scroll">Indicates to skip count query.</param>
    /// <param name="email">Filter the returned members by email address prefix.</param>
    /// <param name="userId">Search for a member by user id.</param>
    /// <param name="status">Filter the returned members by the membership status.</param>
    /// <param name="roles">Filter the returned members by role.</param>
    /// <param name="cancellationToken">Token used to cancel the request.</param>
    public async Task<ApiResponse<MembersListResponse>> ListAsync(string merchantCode, int? offset = null, int? limit = null, bool? scroll = null, string? email = null, Guid? userId = null, MembershipStatus? status = null, IEnumerable<string>? roles = null, CancellationToken cancellationToken = default)
    {
        var request = _client.CreateRequest(HttpMethod.Get, "/v0.1/merchants/{merchant_code}/members", builder =>
        {
            builder.AddPath("merchant_code", merchantCode);
            builder.AddQuery("offset", offset);
            builder.AddQuery("limit", limit);
            builder.AddQuery("scroll", scroll);
            builder.AddQuery("email", email);
            builder.AddQuery("user.id", userId);
            builder.AddQuery("status", status);
            builder.AddQuery("roles", roles);
        });
        return await _client.SendAsync<MembersListResponse>(request, null, null, cancellationToken).ConfigureAwait(false);
    }

    /// <summary>
    /// Update a member
    /// </summary>
    /// <remarks>Update the merchant member.</remarks>
    /// <param name="merchantCode">Short unique identifier for the merchant.</param>
    /// <param name="memberId">The ID of the member to retrieve.</param>
    /// <param name="body">Request body payload.</param>
    /// <param name="cancellationToken">Token used to cancel the request.</param>
    public ApiResponse<Member> Update(string merchantCode, string memberId, MembersUpdateRequest body, CancellationToken cancellationToken = default)
    {
        var request = _client.CreateRequest(HttpMethod.Put, "/v0.1/merchants/{merchant_code}/members/{member_id}", builder =>
        {
            builder.AddPath("merchant_code", merchantCode);
            builder.AddPath("member_id", memberId);
        });
        return _client.Send<Member>(request, body, "application/json", cancellationToken);
    }

    /// <summary>
    /// Update a member
    /// </summary>
    /// <remarks>Update the merchant member.</remarks>
    /// <param name="merchantCode">Short unique identifier for the merchant.</param>
    /// <param name="memberId">The ID of the member to retrieve.</param>
    /// <param name="body">Request body payload.</param>
    /// <param name="cancellationToken">Token used to cancel the request.</param>
    public async Task<ApiResponse<Member>> UpdateAsync(string merchantCode, string memberId, MembersUpdateRequest body, CancellationToken cancellationToken = default)
    {
        var request = _client.CreateRequest(HttpMethod.Put, "/v0.1/merchants/{merchant_code}/members/{member_id}", builder =>
        {
            builder.AddPath("merchant_code", merchantCode);
            builder.AddPath("member_id", memberId);
        });
        return await _client.SendAsync<Member>(request, body, "application/json", cancellationToken).ConfigureAwait(false);
    }
}