// <auto-generated />
#nullable enable

namespace SumUp;

using System;
using System.Net.Http;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using SumUp.Http;

public sealed partial class MembershipsClient
{
    private readonly ApiClient _client;

    internal MembershipsClient(ApiClient client)
    {
        _client = client;
    }

    /// <summary>
    /// List memberships
    /// </summary>
    /// <remarks>List memberships of the current user.</remarks>
    /// <param name="offset">Offset of the first member to return.</param>
    /// <param name="limit">Maximum number of members to return.</param>
    /// <param name="kind">Filter memberships by resource kind.</param>
    /// <param name="status">Filter the returned memberships by the membership status.</param>
    /// <param name="resourceType">Filter memberships by resource kind.</param>
    /// <param name="resourceAttributesSandbox">Filter memberships by the sandbox status of the resource the membership is in.</param>
    /// <param name="resourceName">Filter memberships by the name of the resource the membership is in.</param>
    /// <param name="resourceParentId">Filter memberships by the parent of the resource the membership is in. When filtering by parent both `resource.parent.id` and `resource.parent.type` must be present. Pass explicit null to filter for resources without a parent.</param>
    /// <param name="resourceParentType">Filter memberships by the parent of the resource the membership is in. When filtering by parent both `resource.parent.id` and `resource.parent.type` must be present. Pass explicit null to filter for resources without a parent.</param>
    /// <param name="roles">Filter the returned memberships by role.</param>
    /// <param name="requestOptions">Optional per-request overrides.</param>
    /// <param name="cancellationToken">Token used to cancel the request.</param>
    public ApiResponse<MembershipsListResponse> List(int? offset = null, int? limit = null, string? kind = null, MembershipStatus? status = null, string? resourceType = null, bool? resourceAttributesSandbox = null, string? resourceName = null, OptionalQuery<string> resourceParentId = default, OptionalQuery<string> resourceParentType = default, IEnumerable<string>? roles = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        var request = _client.CreateRequest(HttpMethod.Get, "/v0.1/memberships", builder =>
        {
            builder.AddQuery("offset", offset);
            builder.AddQuery("limit", limit);
            builder.AddQuery("kind", kind);
            builder.AddQuery("status", status);
            builder.AddQuery("resource.type", resourceType);
            builder.AddQuery("resource.attributes.sandbox", resourceAttributesSandbox);
            builder.AddQuery("resource.name", resourceName);
            builder.AddQuery("resource.parent.id", resourceParentId);
            builder.AddQuery("resource.parent.type", resourceParentType);
            builder.AddQuery("roles", roles);
        });
        var effectiveCancellationToken = ApiClient.CreateCancellationToken(cancellationToken, requestOptions, out var timeoutScope);
        try
        {
            _client.ApplyAuthorizationHeaderAsync(request, effectiveCancellationToken, requestOptions).GetAwaiter().GetResult();

            using var response = _client.HttpClient.SendAsync(
                request,
                HttpCompletionOption.ResponseHeadersRead,
                effectiveCancellationToken).GetAwaiter().GetResult();

            if (!response.IsSuccessStatusCode)
            {
                var responseBody = response.Content is null
                    ? null
                    : ApiClient.ReadContentAsStringAsync(response.Content, effectiveCancellationToken).GetAwaiter().GetResult();
                var fallbackError = _client.TryDeserialize<ApiError>(responseBody);
                throw new ApiException(response.StatusCode, fallbackError, responseBody, response.RequestMessage?.RequestUri);
            }
            using var stream = ApiClient.ReadContentAsStreamAsync(response.Content!, effectiveCancellationToken).GetAwaiter().GetResult();
            var result = JsonSerializer.Deserialize<MembershipsListResponse>(stream, _client.SerializerOptions);
            return ApiResponse<MembershipsListResponse>.From(result, response.StatusCode, response.Headers, response.RequestMessage?.RequestUri);
        }
        finally
        {
            timeoutScope?.Dispose();
        }
    }

    /// <summary>
    /// List memberships
    /// </summary>
    /// <remarks>List memberships of the current user.</remarks>
    /// <param name="offset">Offset of the first member to return.</param>
    /// <param name="limit">Maximum number of members to return.</param>
    /// <param name="kind">Filter memberships by resource kind.</param>
    /// <param name="status">Filter the returned memberships by the membership status.</param>
    /// <param name="resourceType">Filter memberships by resource kind.</param>
    /// <param name="resourceAttributesSandbox">Filter memberships by the sandbox status of the resource the membership is in.</param>
    /// <param name="resourceName">Filter memberships by the name of the resource the membership is in.</param>
    /// <param name="resourceParentId">Filter memberships by the parent of the resource the membership is in. When filtering by parent both `resource.parent.id` and `resource.parent.type` must be present. Pass explicit null to filter for resources without a parent.</param>
    /// <param name="resourceParentType">Filter memberships by the parent of the resource the membership is in. When filtering by parent both `resource.parent.id` and `resource.parent.type` must be present. Pass explicit null to filter for resources without a parent.</param>
    /// <param name="roles">Filter the returned memberships by role.</param>
    /// <param name="requestOptions">Optional per-request overrides.</param>
    /// <param name="cancellationToken">Token used to cancel the request.</param>
    public async Task<ApiResponse<MembershipsListResponse>> ListAsync(int? offset = null, int? limit = null, string? kind = null, MembershipStatus? status = null, string? resourceType = null, bool? resourceAttributesSandbox = null, string? resourceName = null, OptionalQuery<string> resourceParentId = default, OptionalQuery<string> resourceParentType = default, IEnumerable<string>? roles = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        var request = _client.CreateRequest(HttpMethod.Get, "/v0.1/memberships", builder =>
        {
            builder.AddQuery("offset", offset);
            builder.AddQuery("limit", limit);
            builder.AddQuery("kind", kind);
            builder.AddQuery("status", status);
            builder.AddQuery("resource.type", resourceType);
            builder.AddQuery("resource.attributes.sandbox", resourceAttributesSandbox);
            builder.AddQuery("resource.name", resourceName);
            builder.AddQuery("resource.parent.id", resourceParentId);
            builder.AddQuery("resource.parent.type", resourceParentType);
            builder.AddQuery("roles", roles);
        });
        var effectiveCancellationToken = ApiClient.CreateCancellationToken(cancellationToken, requestOptions, out var timeoutScope);
        try
        {
            await _client.ApplyAuthorizationHeaderAsync(request, effectiveCancellationToken, requestOptions).ConfigureAwait(false);

            using var response = await _client.HttpClient.SendAsync(
                request,
                HttpCompletionOption.ResponseHeadersRead,
                effectiveCancellationToken).ConfigureAwait(false);

            if (!response.IsSuccessStatusCode)
            {
                var responseBody = response.Content is null
                    ? null
                    : await ApiClient.ReadContentAsStringAsync(response.Content, effectiveCancellationToken).ConfigureAwait(false);
                var fallbackError = _client.TryDeserialize<ApiError>(responseBody);
                throw new ApiException(response.StatusCode, fallbackError, responseBody, response.RequestMessage?.RequestUri);
            }
            using var stream = await ApiClient.ReadContentAsStreamAsync(response.Content!, effectiveCancellationToken).ConfigureAwait(false);
            var result = await JsonSerializer.DeserializeAsync<MembershipsListResponse>(stream, _client.SerializerOptions, effectiveCancellationToken).ConfigureAwait(false);
            return ApiResponse<MembershipsListResponse>.From(result, response.StatusCode, response.Headers, response.RequestMessage?.RequestUri);
        }
        finally
        {
            timeoutScope?.Dispose();
        }
    }
}