// <auto-generated />
#nullable enable

namespace SumUp;

using System;
using System.Net.Http;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using SumUp.Http;

public sealed partial class MerchantsClient
{
    private readonly ApiClient _client;

    internal MerchantsClient(ApiClient client)
    {
        _client = client;
    }

    /// <summary>
    /// Retrieve a Merchant
    /// </summary>
    /// <remarks>Retrieve a merchant.</remarks>
    /// <param name="merchantCode">Short unique identifier for the merchant.</param>
    /// <param name="version">The version of the resource. At the moment, the only supported value is `latest`. When provided and the requested resource's `change_status` is pending, the resource will be returned with all pending changes applied. When no changes are pending the resource is returned as is. The `change_status` in the response body will reflect the current state of the resource.</param>
    /// <param name="cancellationToken">Token used to cancel the request.</param>
    public ApiResponse<Merchant> Get(string merchantCode, string? version = null, CancellationToken cancellationToken = default)
    {
        var request = _client.CreateRequest(HttpMethod.Get, "/v1/merchants/{merchant_code}", builder =>
        {
            builder.AddPath("merchant_code", merchantCode);
            builder.AddQuery("version", version);
        });
        return _client.Send<Merchant>(request, null, null, cancellationToken);
    }

    /// <summary>
    /// Retrieve a Merchant
    /// </summary>
    /// <remarks>Retrieve a merchant.</remarks>
    /// <param name="merchantCode">Short unique identifier for the merchant.</param>
    /// <param name="version">The version of the resource. At the moment, the only supported value is `latest`. When provided and the requested resource's `change_status` is pending, the resource will be returned with all pending changes applied. When no changes are pending the resource is returned as is. The `change_status` in the response body will reflect the current state of the resource.</param>
    /// <param name="cancellationToken">Token used to cancel the request.</param>
    public async Task<ApiResponse<Merchant>> GetAsync(string merchantCode, string? version = null, CancellationToken cancellationToken = default)
    {
        var request = _client.CreateRequest(HttpMethod.Get, "/v1/merchants/{merchant_code}", builder =>
        {
            builder.AddPath("merchant_code", merchantCode);
            builder.AddQuery("version", version);
        });
        return await _client.SendAsync<Merchant>(request, null, null, cancellationToken).ConfigureAwait(false);
    }

    /// <summary>
    /// Retrieve a Person
    /// </summary>
    /// <remarks>Returns a single person related to the merchant.</remarks>
    /// <param name="merchantCode">Short unique identifier for the merchant.</param>
    /// <param name="personId">Person ID</param>
    /// <param name="version">The version of the resource. At the moment, the only supported value is `latest`. When provided and the requested resource's `change_status` is pending, the resource will be returned with all pending changes applied. When no changes are pending the resource is returned as is. The `change_status` in the response body will reflect the current state of the resource.</param>
    /// <param name="cancellationToken">Token used to cancel the request.</param>
    public ApiResponse<Person> GetPerson(string merchantCode, string personId, string? version = null, CancellationToken cancellationToken = default)
    {
        var request = _client.CreateRequest(HttpMethod.Get, "/v1/merchants/{merchant_code}/persons/{person_id}", builder =>
        {
            builder.AddPath("merchant_code", merchantCode);
            builder.AddPath("person_id", personId);
            builder.AddQuery("version", version);
        });
        return _client.Send<Person>(request, null, null, cancellationToken);
    }

    /// <summary>
    /// Retrieve a Person
    /// </summary>
    /// <remarks>Returns a single person related to the merchant.</remarks>
    /// <param name="merchantCode">Short unique identifier for the merchant.</param>
    /// <param name="personId">Person ID</param>
    /// <param name="version">The version of the resource. At the moment, the only supported value is `latest`. When provided and the requested resource's `change_status` is pending, the resource will be returned with all pending changes applied. When no changes are pending the resource is returned as is. The `change_status` in the response body will reflect the current state of the resource.</param>
    /// <param name="cancellationToken">Token used to cancel the request.</param>
    public async Task<ApiResponse<Person>> GetPersonAsync(string merchantCode, string personId, string? version = null, CancellationToken cancellationToken = default)
    {
        var request = _client.CreateRequest(HttpMethod.Get, "/v1/merchants/{merchant_code}/persons/{person_id}", builder =>
        {
            builder.AddPath("merchant_code", merchantCode);
            builder.AddPath("person_id", personId);
            builder.AddQuery("version", version);
        });
        return await _client.SendAsync<Person>(request, null, null, cancellationToken).ConfigureAwait(false);
    }

    /// <summary>
    /// List Persons
    /// </summary>
    /// <remarks>Returns a list of persons related to the merchant.</remarks>
    /// <param name="merchantCode">Short unique identifier for the merchant.</param>
    /// <param name="version">The version of the resource. At the moment, the only supported value is `latest`. When provided and the requested resource's `change_status` is pending, the resource will be returned with all pending changes applied. When no changes are pending the resource is returned as is. The `change_status` in the response body will reflect the current state of the resource.</param>
    /// <param name="cancellationToken">Token used to cancel the request.</param>
    public ApiResponse<ListPersonsResponseBody> ListPersons(string merchantCode, string? version = null, CancellationToken cancellationToken = default)
    {
        var request = _client.CreateRequest(HttpMethod.Get, "/v1/merchants/{merchant_code}/persons", builder =>
        {
            builder.AddPath("merchant_code", merchantCode);
            builder.AddQuery("version", version);
        });
        return _client.Send<ListPersonsResponseBody>(request, null, null, cancellationToken);
    }

    /// <summary>
    /// List Persons
    /// </summary>
    /// <remarks>Returns a list of persons related to the merchant.</remarks>
    /// <param name="merchantCode">Short unique identifier for the merchant.</param>
    /// <param name="version">The version of the resource. At the moment, the only supported value is `latest`. When provided and the requested resource's `change_status` is pending, the resource will be returned with all pending changes applied. When no changes are pending the resource is returned as is. The `change_status` in the response body will reflect the current state of the resource.</param>
    /// <param name="cancellationToken">Token used to cancel the request.</param>
    public async Task<ApiResponse<ListPersonsResponseBody>> ListPersonsAsync(string merchantCode, string? version = null, CancellationToken cancellationToken = default)
    {
        var request = _client.CreateRequest(HttpMethod.Get, "/v1/merchants/{merchant_code}/persons", builder =>
        {
            builder.AddPath("merchant_code", merchantCode);
            builder.AddQuery("version", version);
        });
        return await _client.SendAsync<ListPersonsResponseBody>(request, null, null, cancellationToken).ConfigureAwait(false);
    }
}