// <auto-generated />
#nullable enable

namespace SumUp;

using System;
using System.Net.Http;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using SumUp.Http;

public sealed partial class PayoutsClient
{
    private readonly ApiClient _client;

    internal PayoutsClient(ApiClient client)
    {
        _client = client;
    }

    /// <summary>
    /// List payouts
    /// </summary>
    /// <remarks>Lists ordered payouts for the merchant profile.</remarks>
    /// <param name="merchantCode">Request parameter.</param>
    /// <param name="startDate">Start date (in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) format).</param>
    /// <param name="endDate">End date (in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) format).</param>
    /// <param name="format">Request parameter.</param>
    /// <param name="limit">Request parameter.</param>
    /// <param name="order">Request parameter.</param>
    /// <param name="cancellationToken">Token used to cancel the request.</param>
    public ApiResponse<IEnumerable<JsonDocument>> List(string merchantCode, DateTime startDate, DateTime endDate, string? format = null, int? limit = null, string? order = null, CancellationToken cancellationToken = default)
    {
        var request = _client.CreateRequest(HttpMethod.Get, "/v1.0/merchants/{merchant_code}/payouts", builder =>
        {
            builder.AddPath("merchant_code", merchantCode);
            builder.AddQuery("start_date", startDate);
            builder.AddQuery("end_date", endDate);
            builder.AddQuery("format", format);
            builder.AddQuery("limit", limit);
            builder.AddQuery("order", order);
        });
        return _client.Send<IEnumerable<JsonDocument>>(request, null, null, cancellationToken);
    }

    /// <summary>
    /// List payouts
    /// </summary>
    /// <remarks>Lists ordered payouts for the merchant profile.</remarks>
    /// <param name="merchantCode">Request parameter.</param>
    /// <param name="startDate">Start date (in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) format).</param>
    /// <param name="endDate">End date (in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) format).</param>
    /// <param name="format">Request parameter.</param>
    /// <param name="limit">Request parameter.</param>
    /// <param name="order">Request parameter.</param>
    /// <param name="cancellationToken">Token used to cancel the request.</param>
    public async Task<ApiResponse<IEnumerable<JsonDocument>>> ListAsync(string merchantCode, DateTime startDate, DateTime endDate, string? format = null, int? limit = null, string? order = null, CancellationToken cancellationToken = default)
    {
        var request = _client.CreateRequest(HttpMethod.Get, "/v1.0/merchants/{merchant_code}/payouts", builder =>
        {
            builder.AddPath("merchant_code", merchantCode);
            builder.AddQuery("start_date", startDate);
            builder.AddQuery("end_date", endDate);
            builder.AddQuery("format", format);
            builder.AddQuery("limit", limit);
            builder.AddQuery("order", order);
        });
        return await _client.SendAsync<IEnumerable<JsonDocument>>(request, null, null, cancellationToken).ConfigureAwait(false);
    }

    /// <summary>
    /// List payouts
    /// </summary>
    /// <remarks>Lists ordered payouts for the merchant profile.</remarks>
    /// <param name="startDate">Start date (in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) format).</param>
    /// <param name="endDate">End date (in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) format).</param>
    /// <param name="format">Request parameter.</param>
    /// <param name="limit">Request parameter.</param>
    /// <param name="order">Request parameter.</param>
    /// <param name="cancellationToken">Token used to cancel the request.</param>
    public ApiResponse<IEnumerable<JsonDocument>> ListDeprecated(DateTime startDate, DateTime endDate, string? format = null, int? limit = null, string? order = null, CancellationToken cancellationToken = default)
    {
        var request = _client.CreateRequest(HttpMethod.Get, "/v0.1/me/financials/payouts", builder =>
        {
            builder.AddQuery("start_date", startDate);
            builder.AddQuery("end_date", endDate);
            builder.AddQuery("format", format);
            builder.AddQuery("limit", limit);
            builder.AddQuery("order", order);
        });
        return _client.Send<IEnumerable<JsonDocument>>(request, null, null, cancellationToken);
    }

    /// <summary>
    /// List payouts
    /// </summary>
    /// <remarks>Lists ordered payouts for the merchant profile.</remarks>
    /// <param name="startDate">Start date (in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) format).</param>
    /// <param name="endDate">End date (in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) format).</param>
    /// <param name="format">Request parameter.</param>
    /// <param name="limit">Request parameter.</param>
    /// <param name="order">Request parameter.</param>
    /// <param name="cancellationToken">Token used to cancel the request.</param>
    public async Task<ApiResponse<IEnumerable<JsonDocument>>> ListDeprecatedAsync(DateTime startDate, DateTime endDate, string? format = null, int? limit = null, string? order = null, CancellationToken cancellationToken = default)
    {
        var request = _client.CreateRequest(HttpMethod.Get, "/v0.1/me/financials/payouts", builder =>
        {
            builder.AddQuery("start_date", startDate);
            builder.AddQuery("end_date", endDate);
            builder.AddQuery("format", format);
            builder.AddQuery("limit", limit);
            builder.AddQuery("order", order);
        });
        return await _client.SendAsync<IEnumerable<JsonDocument>>(request, null, null, cancellationToken).ConfigureAwait(false);
    }
}