// <auto-generated />
#nullable enable

namespace SumUp;

using System;
using System.Net.Http;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using SumUp.Http;

public sealed partial class SubaccountsClient
{
    private readonly ApiClient _client;

    internal SubaccountsClient(ApiClient client)
    {
        _client = client;
    }

    /// <summary>
    /// Retrieve an operator
    /// </summary>
    /// <remarks>Returns specific operator.</remarks>
    /// <param name="operatorId">The unique identifier for the operator.</param>
    /// <param name="requestOptions">Optional per-request overrides.</param>
    /// <param name="cancellationToken">Token used to cancel the request.</param>
    public ApiResponse<OperatorValue> CompatGetOperator(int operatorId, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        var request = _client.CreateRequest(HttpMethod.Get, "/v0.1/me/accounts/{operator_id}", builder =>
        {
            builder.AddPath("operator_id", operatorId);
        });
        return _client.Send<OperatorValue>(request, null, null, cancellationToken, requestOptions);
    }

    /// <summary>
    /// Retrieve an operator
    /// </summary>
    /// <remarks>Returns specific operator.</remarks>
    /// <param name="operatorId">The unique identifier for the operator.</param>
    /// <param name="requestOptions">Optional per-request overrides.</param>
    /// <param name="cancellationToken">Token used to cancel the request.</param>
    public async Task<ApiResponse<OperatorValue>> CompatGetOperatorAsync(int operatorId, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        var request = _client.CreateRequest(HttpMethod.Get, "/v0.1/me/accounts/{operator_id}", builder =>
        {
            builder.AddPath("operator_id", operatorId);
        });
        return await _client.SendAsync<OperatorValue>(request, null, null, cancellationToken, requestOptions).ConfigureAwait(false);
    }

    /// <summary>
    /// Create an operator
    /// </summary>
    /// <remarks>Creates new operator for currently authorized users' merchant.</remarks>
    /// <param name="body">Request body payload.</param>
    /// <param name="requestOptions">Optional per-request overrides.</param>
    /// <param name="cancellationToken">Token used to cancel the request.</param>
    public ApiResponse<OperatorValue> CreateSubAccount(SubaccountsCreateSubAccountRequest body, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        var request = _client.CreateRequest(HttpMethod.Post, "/v0.1/me/accounts");
        return _client.Send<OperatorValue>(request, body, "application/json", cancellationToken, requestOptions);
    }

    /// <summary>
    /// Create an operator
    /// </summary>
    /// <remarks>Creates new operator for currently authorized users' merchant.</remarks>
    /// <param name="body">Request body payload.</param>
    /// <param name="requestOptions">Optional per-request overrides.</param>
    /// <param name="cancellationToken">Token used to cancel the request.</param>
    public async Task<ApiResponse<OperatorValue>> CreateSubAccountAsync(SubaccountsCreateSubAccountRequest body, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        var request = _client.CreateRequest(HttpMethod.Post, "/v0.1/me/accounts");
        return await _client.SendAsync<OperatorValue>(request, body, "application/json", cancellationToken, requestOptions).ConfigureAwait(false);
    }

    /// <summary>
    /// Disable an operator.
    /// </summary>
    /// <remarks>Disable the specified operator for the merchant account.</remarks>
    /// <param name="operatorId">The unique identifier for the operator.</param>
    /// <param name="requestOptions">Optional per-request overrides.</param>
    /// <param name="cancellationToken">Token used to cancel the request.</param>
    public ApiResponse<OperatorValue> DeactivateSubAccount(int operatorId, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        var request = _client.CreateRequest(HttpMethod.Delete, "/v0.1/me/accounts/{operator_id}", builder =>
        {
            builder.AddPath("operator_id", operatorId);
        });
        return _client.Send<OperatorValue>(request, null, null, cancellationToken, requestOptions);
    }

    /// <summary>
    /// Disable an operator.
    /// </summary>
    /// <remarks>Disable the specified operator for the merchant account.</remarks>
    /// <param name="operatorId">The unique identifier for the operator.</param>
    /// <param name="requestOptions">Optional per-request overrides.</param>
    /// <param name="cancellationToken">Token used to cancel the request.</param>
    public async Task<ApiResponse<OperatorValue>> DeactivateSubAccountAsync(int operatorId, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        var request = _client.CreateRequest(HttpMethod.Delete, "/v0.1/me/accounts/{operator_id}", builder =>
        {
            builder.AddPath("operator_id", operatorId);
        });
        return await _client.SendAsync<OperatorValue>(request, null, null, cancellationToken, requestOptions).ConfigureAwait(false);
    }

    /// <summary>
    /// List operators
    /// </summary>
    /// <remarks>Returns list of operators for currently authorized user's merchant.</remarks>
    /// <param name="query">Search query used to filter users that match given query term. Current implementation allow querying only over the email address. All operators whos email address contains the query string are returned.</param>
    /// <param name="includePrimary">If true the list of operators will include also the primary user.</param>
    /// <param name="requestOptions">Optional per-request overrides.</param>
    /// <param name="cancellationToken">Token used to cancel the request.</param>
    public ApiResponse<IEnumerable<OperatorValue>> ListSubAccounts(string? query = null, bool? includePrimary = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        var request = _client.CreateRequest(HttpMethod.Get, "/v0.1/me/accounts", builder =>
        {
            builder.AddQuery("query", query);
            builder.AddQuery("include_primary", includePrimary);
        });
        return _client.Send<IEnumerable<OperatorValue>>(request, null, null, cancellationToken, requestOptions);
    }

    /// <summary>
    /// List operators
    /// </summary>
    /// <remarks>Returns list of operators for currently authorized user's merchant.</remarks>
    /// <param name="query">Search query used to filter users that match given query term. Current implementation allow querying only over the email address. All operators whos email address contains the query string are returned.</param>
    /// <param name="includePrimary">If true the list of operators will include also the primary user.</param>
    /// <param name="requestOptions">Optional per-request overrides.</param>
    /// <param name="cancellationToken">Token used to cancel the request.</param>
    public async Task<ApiResponse<IEnumerable<OperatorValue>>> ListSubAccountsAsync(string? query = null, bool? includePrimary = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        var request = _client.CreateRequest(HttpMethod.Get, "/v0.1/me/accounts", builder =>
        {
            builder.AddQuery("query", query);
            builder.AddQuery("include_primary", includePrimary);
        });
        return await _client.SendAsync<IEnumerable<OperatorValue>>(request, null, null, cancellationToken, requestOptions).ConfigureAwait(false);
    }

    /// <summary>
    /// Update an operator
    /// </summary>
    /// <remarks>Updates operator. If the operator was disabled and their password is updated they will be unblocked.</remarks>
    /// <param name="operatorId">The unique identifier for the operator.</param>
    /// <param name="body">Request body payload.</param>
    /// <param name="requestOptions">Optional per-request overrides.</param>
    /// <param name="cancellationToken">Token used to cancel the request.</param>
    public ApiResponse<OperatorValue> UpdateSubAccount(int operatorId, SubaccountsUpdateSubAccountRequest body, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        var request = _client.CreateRequest(HttpMethod.Put, "/v0.1/me/accounts/{operator_id}", builder =>
        {
            builder.AddPath("operator_id", operatorId);
        });
        return _client.Send<OperatorValue>(request, body, "application/json", cancellationToken, requestOptions);
    }

    /// <summary>
    /// Update an operator
    /// </summary>
    /// <remarks>Updates operator. If the operator was disabled and their password is updated they will be unblocked.</remarks>
    /// <param name="operatorId">The unique identifier for the operator.</param>
    /// <param name="body">Request body payload.</param>
    /// <param name="requestOptions">Optional per-request overrides.</param>
    /// <param name="cancellationToken">Token used to cancel the request.</param>
    public async Task<ApiResponse<OperatorValue>> UpdateSubAccountAsync(int operatorId, SubaccountsUpdateSubAccountRequest body, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        var request = _client.CreateRequest(HttpMethod.Put, "/v0.1/me/accounts/{operator_id}", builder =>
        {
            builder.AddPath("operator_id", operatorId);
        });
        return await _client.SendAsync<OperatorValue>(request, body, "application/json", cancellationToken, requestOptions).ConfigureAwait(false);
    }
}