// <auto-generated />
#nullable enable

namespace SumUp;

using SumUp.Http;

public partial class SumUpClient
{
    partial void InitializeGeneratedClients(ApiClient apiClient)
    {
        Checkouts = new CheckoutsClient(apiClient);
        Customers = new CustomersClient(apiClient);
        Members = new MembersClient(apiClient);
        Memberships = new MembershipsClient(apiClient);
        Merchants = new MerchantsClient(apiClient);
        Payouts = new PayoutsClient(apiClient);
        Readers = new ReadersClient(apiClient);
        Receipts = new ReceiptsClient(apiClient);
        Roles = new RolesClient(apiClient);
        Subaccounts = new SubaccountsClient(apiClient);
        Transactions = new TransactionsClient(apiClient);
    }

    public CheckoutsClient Checkouts { get; private set; } = default!;

    public CustomersClient Customers { get; private set; } = default!;

    public MembersClient Members { get; private set; } = default!;

    public MembershipsClient Memberships { get; private set; } = default!;

    public MerchantsClient Merchants { get; private set; } = default!;

    public PayoutsClient Payouts { get; private set; } = default!;

    public ReadersClient Readers { get; private set; } = default!;

    public ReceiptsClient Receipts { get; private set; } = default!;

    public RolesClient Roles { get; private set; } = default!;

    public SubaccountsClient Subaccounts { get; private set; } = default!;

    public TransactionsClient Transactions { get; private set; } = default!;
}