// <auto-generated />
#nullable enable

namespace SumUp;

using System;
using System.Net.Http;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using System.Collections.Generic;
using SumUp.Http;

public sealed partial class TransactionsClient
{
    private readonly ApiClient _client;

    /// <summary>
    /// Client for the Transactions API endpoints.
    /// </summary>
    /// <remarks>Transactions represent completed or attempted payment operations processed for a merchant account. A transaction contains the core payment result, such as the amount, currency, payment method, creation time, and current high-level status. In addition to the main payment outcome, a transaction can contain related events that describe what happened after the original payment attempt. These events provide visibility into the financial lifecycle of the transaction, for example: - `PAYOUT`: the payment being prepared for payout or included in a payout to the merchant - `REFUND`: money returned to the payer - `CHARGE_BACK`: money reversed after the original payment - `PAYOUT_DEDUCTION`: an amount deducted from a payout to cover a refund or chargeback From an integrator's perspective, transactions are the authoritative record of payment outcomes. Use this tag to: - list transactions for reporting, reconciliation, and customer support workflows - retrieve a single transaction when you need the latest payment details - inspect `simple_status` for the current merchant-facing outcome of the payment - inspect `events` or `transaction_events` when you need refund, payout, or chargeback history Typical workflow: - create and process payments through the Checkouts endpoints - use the Transactions endpoints to read the resulting payment records - use the returned statuses and events to update your own order, accounting, or support systems</remarks>
    internal TransactionsClient(ApiClient client)
    {
        _client = client;
    }

    /// <summary>
    /// Retrieve a transaction
    /// </summary>
    /// <remarks>Retrieves the full details of an identified transaction. The transaction resource is identified by a query parameter and *one* of following parameters is required: - `id` - `transaction_code` - `foreign_transaction_id` - `client_transaction_id`</remarks>
    /// <param name="merchantCode">Merchant code of the account whose transaction should be retrieved.</param>
    /// <param name="options">Query and header parameters for the request.</param>
    /// <param name="requestOptions">Optional per-request overrides.</param>
    /// <param name="cancellationToken">Token used to cancel the request.</param>
    public ApiResponse<TransactionFull> Get(string merchantCode, TransactionsGetOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        var operationOptions = options ?? new TransactionsGetOptions();
        var request = _client.CreateRequest(HttpMethod.Get, "/v2.1/merchants/{merchant_code}/transactions", builder =>
        {
            builder.AddPath("merchant_code", merchantCode);
            builder.AddQuery("id", operationOptions.Id);
            builder.AddQuery("transaction_code", operationOptions.TransactionCode);
            builder.AddQuery("foreign_transaction_id", operationOptions.ForeignTransactionId);
            builder.AddQuery("client_transaction_id", operationOptions.ClientTransactionId);
        });
        var effectiveCancellationToken = ApiClient.CreateCancellationToken(cancellationToken, requestOptions, out var timeoutScope);
        try
        {
            _client.ApplyAuthorizationHeaderAsync(request, effectiveCancellationToken, requestOptions).GetAwaiter().GetResult();

            using var response = _client.HttpClient.SendAsync(
                request,
                HttpCompletionOption.ResponseHeadersRead,
                effectiveCancellationToken).GetAwaiter().GetResult();

            if (!response.IsSuccessStatusCode)
            {
                var responseBody = response.Content is null
                    ? null
                    : ApiClient.ReadContentAsStringAsync(response.Content, effectiveCancellationToken).GetAwaiter().GetResult();
                switch ((int)response.StatusCode)
                {
                    case 401:
                    {
                        var errorForStatus401 = _client.TryDeserialize<Problem>(responseBody);
                        throw new ApiException<Problem>(response.StatusCode, errorForStatus401, responseBody, response.RequestMessage?.RequestUri);
                    }
                    case 404:
                    {
                        var errorForStatus404 = _client.TryDeserialize<Error>(responseBody);
                        throw new ApiException<Error>(response.StatusCode, errorForStatus404, responseBody, response.RequestMessage?.RequestUri);
                    }
                }
                var fallbackError = _client.TryDeserialize<ApiError>(responseBody);
                throw new ApiException(response.StatusCode, fallbackError, responseBody, response.RequestMessage?.RequestUri);
            }
            using var stream = ApiClient.ReadContentAsStreamAsync(response.Content!, effectiveCancellationToken).GetAwaiter().GetResult();
            var result = JsonSerializer.Deserialize<TransactionFull>(stream, _client.SerializerOptions);
            return ApiResponse<TransactionFull>.From(result, response.StatusCode, response.Headers, response.RequestMessage?.RequestUri);
        }
        finally
        {
            timeoutScope?.Dispose();
        }
    }

    /// <summary>
    /// Retrieve a transaction
    /// </summary>
    /// <remarks>Retrieves the full details of an identified transaction. The transaction resource is identified by a query parameter and *one* of following parameters is required: - `id` - `transaction_code` - `foreign_transaction_id` - `client_transaction_id`</remarks>
    /// <param name="merchantCode">Merchant code of the account whose transaction should be retrieved.</param>
    /// <param name="options">Query and header parameters for the request.</param>
    /// <param name="requestOptions">Optional per-request overrides.</param>
    /// <param name="cancellationToken">Token used to cancel the request.</param>
    public async Task<ApiResponse<TransactionFull>> GetAsync(string merchantCode, TransactionsGetOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        var operationOptions = options ?? new TransactionsGetOptions();
        var request = _client.CreateRequest(HttpMethod.Get, "/v2.1/merchants/{merchant_code}/transactions", builder =>
        {
            builder.AddPath("merchant_code", merchantCode);
            builder.AddQuery("id", operationOptions.Id);
            builder.AddQuery("transaction_code", operationOptions.TransactionCode);
            builder.AddQuery("foreign_transaction_id", operationOptions.ForeignTransactionId);
            builder.AddQuery("client_transaction_id", operationOptions.ClientTransactionId);
        });
        var effectiveCancellationToken = ApiClient.CreateCancellationToken(cancellationToken, requestOptions, out var timeoutScope);
        try
        {
            await _client.ApplyAuthorizationHeaderAsync(request, effectiveCancellationToken, requestOptions).ConfigureAwait(false);

            using var response = await _client.HttpClient.SendAsync(
                request,
                HttpCompletionOption.ResponseHeadersRead,
                effectiveCancellationToken).ConfigureAwait(false);

            if (!response.IsSuccessStatusCode)
            {
                var responseBody = response.Content is null
                    ? null
                    : await ApiClient.ReadContentAsStringAsync(response.Content, effectiveCancellationToken).ConfigureAwait(false);
                switch ((int)response.StatusCode)
                {
                    case 401:
                    {
                        var errorForStatus401 = _client.TryDeserialize<Problem>(responseBody);
                        throw new ApiException<Problem>(response.StatusCode, errorForStatus401, responseBody, response.RequestMessage?.RequestUri);
                    }
                    case 404:
                    {
                        var errorForStatus404 = _client.TryDeserialize<Error>(responseBody);
                        throw new ApiException<Error>(response.StatusCode, errorForStatus404, responseBody, response.RequestMessage?.RequestUri);
                    }
                }
                var fallbackError = _client.TryDeserialize<ApiError>(responseBody);
                throw new ApiException(response.StatusCode, fallbackError, responseBody, response.RequestMessage?.RequestUri);
            }
            using var stream = await ApiClient.ReadContentAsStreamAsync(response.Content!, effectiveCancellationToken).ConfigureAwait(false);
            var result = await JsonSerializer.DeserializeAsync<TransactionFull>(stream, _client.SerializerOptions, effectiveCancellationToken).ConfigureAwait(false);
            return ApiResponse<TransactionFull>.From(result, response.StatusCode, response.Headers, response.RequestMessage?.RequestUri);
        }
        finally
        {
            timeoutScope?.Dispose();
        }
    }

    /// <summary>
    /// Retrieve a transaction
    /// </summary>
    /// <remarks>Retrieves the full details of an identified transaction. The transaction resource is identified by a query parameter and *one* of following parameters is required: - `id` - `transaction_code` - `foreign_transaction_id` - `client_transaction_id`</remarks>
    /// <param name="options">Query and header parameters for the request.</param>
    /// <param name="requestOptions">Optional per-request overrides.</param>
    /// <param name="cancellationToken">Token used to cancel the request.</param>
    public ApiResponse<TransactionFull> GetDeprecated(TransactionsGetDeprecatedOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        var operationOptions = options ?? new TransactionsGetDeprecatedOptions();
        var request = _client.CreateRequest(HttpMethod.Get, "/v0.1/me/transactions", builder =>
        {
            builder.AddQuery("id", operationOptions.Id);
            builder.AddQuery("transaction_code", operationOptions.TransactionCode);
        });
        var effectiveCancellationToken = ApiClient.CreateCancellationToken(cancellationToken, requestOptions, out var timeoutScope);
        try
        {
            _client.ApplyAuthorizationHeaderAsync(request, effectiveCancellationToken, requestOptions).GetAwaiter().GetResult();

            using var response = _client.HttpClient.SendAsync(
                request,
                HttpCompletionOption.ResponseHeadersRead,
                effectiveCancellationToken).GetAwaiter().GetResult();

            if (!response.IsSuccessStatusCode)
            {
                var responseBody = response.Content is null
                    ? null
                    : ApiClient.ReadContentAsStringAsync(response.Content, effectiveCancellationToken).GetAwaiter().GetResult();
                switch ((int)response.StatusCode)
                {
                    case 401:
                    {
                        var errorForStatus401 = _client.TryDeserialize<Problem>(responseBody);
                        throw new ApiException<Problem>(response.StatusCode, errorForStatus401, responseBody, response.RequestMessage?.RequestUri);
                    }
                    case 404:
                    {
                        var errorForStatus404 = _client.TryDeserialize<Error>(responseBody);
                        throw new ApiException<Error>(response.StatusCode, errorForStatus404, responseBody, response.RequestMessage?.RequestUri);
                    }
                }
                var fallbackError = _client.TryDeserialize<ApiError>(responseBody);
                throw new ApiException(response.StatusCode, fallbackError, responseBody, response.RequestMessage?.RequestUri);
            }
            using var stream = ApiClient.ReadContentAsStreamAsync(response.Content!, effectiveCancellationToken).GetAwaiter().GetResult();
            var result = JsonSerializer.Deserialize<TransactionFull>(stream, _client.SerializerOptions);
            return ApiResponse<TransactionFull>.From(result, response.StatusCode, response.Headers, response.RequestMessage?.RequestUri);
        }
        finally
        {
            timeoutScope?.Dispose();
        }
    }

    /// <summary>
    /// Retrieve a transaction
    /// </summary>
    /// <remarks>Retrieves the full details of an identified transaction. The transaction resource is identified by a query parameter and *one* of following parameters is required: - `id` - `transaction_code` - `foreign_transaction_id` - `client_transaction_id`</remarks>
    /// <param name="options">Query and header parameters for the request.</param>
    /// <param name="requestOptions">Optional per-request overrides.</param>
    /// <param name="cancellationToken">Token used to cancel the request.</param>
    public async Task<ApiResponse<TransactionFull>> GetDeprecatedAsync(TransactionsGetDeprecatedOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        var operationOptions = options ?? new TransactionsGetDeprecatedOptions();
        var request = _client.CreateRequest(HttpMethod.Get, "/v0.1/me/transactions", builder =>
        {
            builder.AddQuery("id", operationOptions.Id);
            builder.AddQuery("transaction_code", operationOptions.TransactionCode);
        });
        var effectiveCancellationToken = ApiClient.CreateCancellationToken(cancellationToken, requestOptions, out var timeoutScope);
        try
        {
            await _client.ApplyAuthorizationHeaderAsync(request, effectiveCancellationToken, requestOptions).ConfigureAwait(false);

            using var response = await _client.HttpClient.SendAsync(
                request,
                HttpCompletionOption.ResponseHeadersRead,
                effectiveCancellationToken).ConfigureAwait(false);

            if (!response.IsSuccessStatusCode)
            {
                var responseBody = response.Content is null
                    ? null
                    : await ApiClient.ReadContentAsStringAsync(response.Content, effectiveCancellationToken).ConfigureAwait(false);
                switch ((int)response.StatusCode)
                {
                    case 401:
                    {
                        var errorForStatus401 = _client.TryDeserialize<Problem>(responseBody);
                        throw new ApiException<Problem>(response.StatusCode, errorForStatus401, responseBody, response.RequestMessage?.RequestUri);
                    }
                    case 404:
                    {
                        var errorForStatus404 = _client.TryDeserialize<Error>(responseBody);
                        throw new ApiException<Error>(response.StatusCode, errorForStatus404, responseBody, response.RequestMessage?.RequestUri);
                    }
                }
                var fallbackError = _client.TryDeserialize<ApiError>(responseBody);
                throw new ApiException(response.StatusCode, fallbackError, responseBody, response.RequestMessage?.RequestUri);
            }
            using var stream = await ApiClient.ReadContentAsStreamAsync(response.Content!, effectiveCancellationToken).ConfigureAwait(false);
            var result = await JsonSerializer.DeserializeAsync<TransactionFull>(stream, _client.SerializerOptions, effectiveCancellationToken).ConfigureAwait(false);
            return ApiResponse<TransactionFull>.From(result, response.StatusCode, response.Headers, response.RequestMessage?.RequestUri);
        }
        finally
        {
            timeoutScope?.Dispose();
        }
    }

    /// <summary>
    /// List transactions
    /// </summary>
    /// <remarks>Lists detailed history of all transactions associated with the merchant profile.</remarks>
    /// <param name="merchantCode">Merchant code of the account whose transaction history should be listed.</param>
    /// <param name="options">Query and header parameters for the request.</param>
    /// <param name="requestOptions">Optional per-request overrides.</param>
    /// <param name="cancellationToken">Token used to cancel the request.</param>
    public ApiResponse<TransactionsListResponse> List(string merchantCode, TransactionsListOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        var operationOptions = options ?? new TransactionsListOptions();
        var request = _client.CreateRequest(HttpMethod.Get, "/v2.1/merchants/{merchant_code}/transactions/history", builder =>
        {
            builder.AddPath("merchant_code", merchantCode);
            builder.AddQuery("transaction_code", operationOptions.TransactionCode);
            builder.AddQuery("order", operationOptions.Order);
            builder.AddQuery("limit", operationOptions.Limit);
            builder.AddQuery("users", operationOptions.Users);
            builder.AddQuery("statuses[]", operationOptions.Statuses);
            builder.AddQuery("payment_types", operationOptions.PaymentTypes);
            builder.AddQuery("entry_modes[]", operationOptions.EntryModes);
            builder.AddQuery("types", operationOptions.Types);
            builder.AddQuery("changes_since", operationOptions.ChangesSince);
            builder.AddQuery("newest_time", operationOptions.NewestTime);
            builder.AddQuery("newest_ref", operationOptions.NewestRef);
            builder.AddQuery("oldest_time", operationOptions.OldestTime);
            builder.AddQuery("oldest_ref", operationOptions.OldestRef);
        });
        var effectiveCancellationToken = ApiClient.CreateCancellationToken(cancellationToken, requestOptions, out var timeoutScope);
        try
        {
            _client.ApplyAuthorizationHeaderAsync(request, effectiveCancellationToken, requestOptions).GetAwaiter().GetResult();

            using var response = _client.HttpClient.SendAsync(
                request,
                HttpCompletionOption.ResponseHeadersRead,
                effectiveCancellationToken).GetAwaiter().GetResult();

            if (!response.IsSuccessStatusCode)
            {
                var responseBody = response.Content is null
                    ? null
                    : ApiClient.ReadContentAsStringAsync(response.Content, effectiveCancellationToken).GetAwaiter().GetResult();
                switch ((int)response.StatusCode)
                {
                    case 400:
                    {
                        var errorForStatus400 = _client.TryDeserialize<Error>(responseBody);
                        throw new ApiException<Error>(response.StatusCode, errorForStatus400, responseBody, response.RequestMessage?.RequestUri);
                    }
                    case 401:
                    {
                        var errorForStatus401 = _client.TryDeserialize<Problem>(responseBody);
                        throw new ApiException<Problem>(response.StatusCode, errorForStatus401, responseBody, response.RequestMessage?.RequestUri);
                    }
                }
                var fallbackError = _client.TryDeserialize<ApiError>(responseBody);
                throw new ApiException(response.StatusCode, fallbackError, responseBody, response.RequestMessage?.RequestUri);
            }
            using var stream = ApiClient.ReadContentAsStreamAsync(response.Content!, effectiveCancellationToken).GetAwaiter().GetResult();
            var result = JsonSerializer.Deserialize<TransactionsListResponse>(stream, _client.SerializerOptions);
            return ApiResponse<TransactionsListResponse>.From(result, response.StatusCode, response.Headers, response.RequestMessage?.RequestUri);
        }
        finally
        {
            timeoutScope?.Dispose();
        }
    }

    /// <summary>
    /// List transactions
    /// </summary>
    /// <remarks>Lists detailed history of all transactions associated with the merchant profile.</remarks>
    /// <param name="merchantCode">Merchant code of the account whose transaction history should be listed.</param>
    /// <param name="options">Query and header parameters for the request.</param>
    /// <param name="requestOptions">Optional per-request overrides.</param>
    /// <param name="cancellationToken">Token used to cancel the request.</param>
    public async Task<ApiResponse<TransactionsListResponse>> ListAsync(string merchantCode, TransactionsListOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        var operationOptions = options ?? new TransactionsListOptions();
        var request = _client.CreateRequest(HttpMethod.Get, "/v2.1/merchants/{merchant_code}/transactions/history", builder =>
        {
            builder.AddPath("merchant_code", merchantCode);
            builder.AddQuery("transaction_code", operationOptions.TransactionCode);
            builder.AddQuery("order", operationOptions.Order);
            builder.AddQuery("limit", operationOptions.Limit);
            builder.AddQuery("users", operationOptions.Users);
            builder.AddQuery("statuses[]", operationOptions.Statuses);
            builder.AddQuery("payment_types", operationOptions.PaymentTypes);
            builder.AddQuery("entry_modes[]", operationOptions.EntryModes);
            builder.AddQuery("types", operationOptions.Types);
            builder.AddQuery("changes_since", operationOptions.ChangesSince);
            builder.AddQuery("newest_time", operationOptions.NewestTime);
            builder.AddQuery("newest_ref", operationOptions.NewestRef);
            builder.AddQuery("oldest_time", operationOptions.OldestTime);
            builder.AddQuery("oldest_ref", operationOptions.OldestRef);
        });
        var effectiveCancellationToken = ApiClient.CreateCancellationToken(cancellationToken, requestOptions, out var timeoutScope);
        try
        {
            await _client.ApplyAuthorizationHeaderAsync(request, effectiveCancellationToken, requestOptions).ConfigureAwait(false);

            using var response = await _client.HttpClient.SendAsync(
                request,
                HttpCompletionOption.ResponseHeadersRead,
                effectiveCancellationToken).ConfigureAwait(false);

            if (!response.IsSuccessStatusCode)
            {
                var responseBody = response.Content is null
                    ? null
                    : await ApiClient.ReadContentAsStringAsync(response.Content, effectiveCancellationToken).ConfigureAwait(false);
                switch ((int)response.StatusCode)
                {
                    case 400:
                    {
                        var errorForStatus400 = _client.TryDeserialize<Error>(responseBody);
                        throw new ApiException<Error>(response.StatusCode, errorForStatus400, responseBody, response.RequestMessage?.RequestUri);
                    }
                    case 401:
                    {
                        var errorForStatus401 = _client.TryDeserialize<Problem>(responseBody);
                        throw new ApiException<Problem>(response.StatusCode, errorForStatus401, responseBody, response.RequestMessage?.RequestUri);
                    }
                }
                var fallbackError = _client.TryDeserialize<ApiError>(responseBody);
                throw new ApiException(response.StatusCode, fallbackError, responseBody, response.RequestMessage?.RequestUri);
            }
            using var stream = await ApiClient.ReadContentAsStreamAsync(response.Content!, effectiveCancellationToken).ConfigureAwait(false);
            var result = await JsonSerializer.DeserializeAsync<TransactionsListResponse>(stream, _client.SerializerOptions, effectiveCancellationToken).ConfigureAwait(false);
            return ApiResponse<TransactionsListResponse>.From(result, response.StatusCode, response.Headers, response.RequestMessage?.RequestUri);
        }
        finally
        {
            timeoutScope?.Dispose();
        }
    }

    /// <summary>
    /// List transactions
    /// </summary>
    /// <remarks>Lists detailed history of all transactions associated with the merchant profile.</remarks>
    /// <param name="options">Query and header parameters for the request.</param>
    /// <param name="requestOptions">Optional per-request overrides.</param>
    /// <param name="cancellationToken">Token used to cancel the request.</param>
    public ApiResponse<TransactionsListDeprecatedResponse> ListDeprecated(TransactionsListDeprecatedOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        var operationOptions = options ?? new TransactionsListDeprecatedOptions();
        var request = _client.CreateRequest(HttpMethod.Get, "/v0.1/me/transactions/history", builder =>
        {
            builder.AddQuery("transaction_code", operationOptions.TransactionCode);
            builder.AddQuery("order", operationOptions.Order);
            builder.AddQuery("limit", operationOptions.Limit);
            builder.AddQuery("users", operationOptions.Users);
            builder.AddQuery("statuses[]", operationOptions.Statuses);
            builder.AddQuery("payment_types", operationOptions.PaymentTypes);
            builder.AddQuery("types", operationOptions.Types);
            builder.AddQuery("changes_since", operationOptions.ChangesSince);
            builder.AddQuery("newest_time", operationOptions.NewestTime);
            builder.AddQuery("newest_ref", operationOptions.NewestRef);
            builder.AddQuery("oldest_time", operationOptions.OldestTime);
            builder.AddQuery("oldest_ref", operationOptions.OldestRef);
        });
        var effectiveCancellationToken = ApiClient.CreateCancellationToken(cancellationToken, requestOptions, out var timeoutScope);
        try
        {
            _client.ApplyAuthorizationHeaderAsync(request, effectiveCancellationToken, requestOptions).GetAwaiter().GetResult();

            using var response = _client.HttpClient.SendAsync(
                request,
                HttpCompletionOption.ResponseHeadersRead,
                effectiveCancellationToken).GetAwaiter().GetResult();

            if (!response.IsSuccessStatusCode)
            {
                var responseBody = response.Content is null
                    ? null
                    : ApiClient.ReadContentAsStringAsync(response.Content, effectiveCancellationToken).GetAwaiter().GetResult();
                switch ((int)response.StatusCode)
                {
                    case 400:
                    {
                        var errorForStatus400 = _client.TryDeserialize<Error>(responseBody);
                        throw new ApiException<Error>(response.StatusCode, errorForStatus400, responseBody, response.RequestMessage?.RequestUri);
                    }
                    case 401:
                    {
                        var errorForStatus401 = _client.TryDeserialize<Problem>(responseBody);
                        throw new ApiException<Problem>(response.StatusCode, errorForStatus401, responseBody, response.RequestMessage?.RequestUri);
                    }
                }
                var fallbackError = _client.TryDeserialize<ApiError>(responseBody);
                throw new ApiException(response.StatusCode, fallbackError, responseBody, response.RequestMessage?.RequestUri);
            }
            using var stream = ApiClient.ReadContentAsStreamAsync(response.Content!, effectiveCancellationToken).GetAwaiter().GetResult();
            var result = JsonSerializer.Deserialize<TransactionsListDeprecatedResponse>(stream, _client.SerializerOptions);
            return ApiResponse<TransactionsListDeprecatedResponse>.From(result, response.StatusCode, response.Headers, response.RequestMessage?.RequestUri);
        }
        finally
        {
            timeoutScope?.Dispose();
        }
    }

    /// <summary>
    /// List transactions
    /// </summary>
    /// <remarks>Lists detailed history of all transactions associated with the merchant profile.</remarks>
    /// <param name="options">Query and header parameters for the request.</param>
    /// <param name="requestOptions">Optional per-request overrides.</param>
    /// <param name="cancellationToken">Token used to cancel the request.</param>
    public async Task<ApiResponse<TransactionsListDeprecatedResponse>> ListDeprecatedAsync(TransactionsListDeprecatedOptions? options = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        var operationOptions = options ?? new TransactionsListDeprecatedOptions();
        var request = _client.CreateRequest(HttpMethod.Get, "/v0.1/me/transactions/history", builder =>
        {
            builder.AddQuery("transaction_code", operationOptions.TransactionCode);
            builder.AddQuery("order", operationOptions.Order);
            builder.AddQuery("limit", operationOptions.Limit);
            builder.AddQuery("users", operationOptions.Users);
            builder.AddQuery("statuses[]", operationOptions.Statuses);
            builder.AddQuery("payment_types", operationOptions.PaymentTypes);
            builder.AddQuery("types", operationOptions.Types);
            builder.AddQuery("changes_since", operationOptions.ChangesSince);
            builder.AddQuery("newest_time", operationOptions.NewestTime);
            builder.AddQuery("newest_ref", operationOptions.NewestRef);
            builder.AddQuery("oldest_time", operationOptions.OldestTime);
            builder.AddQuery("oldest_ref", operationOptions.OldestRef);
        });
        var effectiveCancellationToken = ApiClient.CreateCancellationToken(cancellationToken, requestOptions, out var timeoutScope);
        try
        {
            await _client.ApplyAuthorizationHeaderAsync(request, effectiveCancellationToken, requestOptions).ConfigureAwait(false);

            using var response = await _client.HttpClient.SendAsync(
                request,
                HttpCompletionOption.ResponseHeadersRead,
                effectiveCancellationToken).ConfigureAwait(false);

            if (!response.IsSuccessStatusCode)
            {
                var responseBody = response.Content is null
                    ? null
                    : await ApiClient.ReadContentAsStringAsync(response.Content, effectiveCancellationToken).ConfigureAwait(false);
                switch ((int)response.StatusCode)
                {
                    case 400:
                    {
                        var errorForStatus400 = _client.TryDeserialize<Error>(responseBody);
                        throw new ApiException<Error>(response.StatusCode, errorForStatus400, responseBody, response.RequestMessage?.RequestUri);
                    }
                    case 401:
                    {
                        var errorForStatus401 = _client.TryDeserialize<Problem>(responseBody);
                        throw new ApiException<Problem>(response.StatusCode, errorForStatus401, responseBody, response.RequestMessage?.RequestUri);
                    }
                }
                var fallbackError = _client.TryDeserialize<ApiError>(responseBody);
                throw new ApiException(response.StatusCode, fallbackError, responseBody, response.RequestMessage?.RequestUri);
            }
            using var stream = await ApiClient.ReadContentAsStreamAsync(response.Content!, effectiveCancellationToken).ConfigureAwait(false);
            var result = await JsonSerializer.DeserializeAsync<TransactionsListDeprecatedResponse>(stream, _client.SerializerOptions, effectiveCancellationToken).ConfigureAwait(false);
            return ApiResponse<TransactionsListDeprecatedResponse>.From(result, response.StatusCode, response.Headers, response.RequestMessage?.RequestUri);
        }
        finally
        {
            timeoutScope?.Dispose();
        }
    }

    /// <summary>
    /// Refund a transaction
    /// </summary>
    /// <remarks>Refunds an identified transaction either in full or partially.</remarks>
    /// <param name="txnId">Unique ID of the transaction.</param>
    /// <param name="body">Optional amount for partial refunds.</param>
    /// <param name="requestOptions">Optional per-request overrides.</param>
    /// <param name="cancellationToken">Token used to cancel the request.</param>
    public ApiResponse<JsonDocument> Refund(string txnId, TransactionsRefundRequest? body = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        var request = _client.CreateRequest(HttpMethod.Post, "/v0.1/me/refund/{txn_id}", builder =>
        {
            builder.AddPath("txn_id", txnId);
        });
        var effectiveCancellationToken = ApiClient.CreateCancellationToken(cancellationToken, requestOptions, out var timeoutScope);
        try
        {
            _client.ApplyAuthorizationHeaderAsync(request, effectiveCancellationToken, requestOptions).GetAwaiter().GetResult();
            if (body is not null && request.Content is null)
            {
                request.Content = _client.CreateContent(body, "application/json");
            }

            using var response = _client.HttpClient.SendAsync(
                request,
                HttpCompletionOption.ResponseHeadersRead,
                effectiveCancellationToken).GetAwaiter().GetResult();

            if (!response.IsSuccessStatusCode)
            {
                var responseBody = response.Content is null
                    ? null
                    : ApiClient.ReadContentAsStringAsync(response.Content, effectiveCancellationToken).GetAwaiter().GetResult();
                switch ((int)response.StatusCode)
                {
                    case 404:
                    {
                        var errorForStatus404 = _client.TryDeserialize<Error>(responseBody);
                        throw new ApiException<Error>(response.StatusCode, errorForStatus404, responseBody, response.RequestMessage?.RequestUri);
                    }
                    case 409:
                    {
                        var errorForStatus409 = _client.TryDeserialize<Error>(responseBody);
                        throw new ApiException<Error>(response.StatusCode, errorForStatus409, responseBody, response.RequestMessage?.RequestUri);
                    }
                }
                var fallbackError = _client.TryDeserialize<ApiError>(responseBody);
                throw new ApiException(response.StatusCode, fallbackError, responseBody, response.RequestMessage?.RequestUri);
            }
            return ApiResponse<JsonDocument>.From(default, response.StatusCode, response.Headers, response.RequestMessage?.RequestUri);
        }
        finally
        {
            timeoutScope?.Dispose();
        }
    }

    /// <summary>
    /// Refund a transaction
    /// </summary>
    /// <remarks>Refunds an identified transaction either in full or partially.</remarks>
    /// <param name="txnId">Unique ID of the transaction.</param>
    /// <param name="body">Optional amount for partial refunds.</param>
    /// <param name="requestOptions">Optional per-request overrides.</param>
    /// <param name="cancellationToken">Token used to cancel the request.</param>
    public async Task<ApiResponse<JsonDocument>> RefundAsync(string txnId, TransactionsRefundRequest? body = null, RequestOptions? requestOptions = null, CancellationToken cancellationToken = default)
    {
        var request = _client.CreateRequest(HttpMethod.Post, "/v0.1/me/refund/{txn_id}", builder =>
        {
            builder.AddPath("txn_id", txnId);
        });
        var effectiveCancellationToken = ApiClient.CreateCancellationToken(cancellationToken, requestOptions, out var timeoutScope);
        try
        {
            await _client.ApplyAuthorizationHeaderAsync(request, effectiveCancellationToken, requestOptions).ConfigureAwait(false);
            if (body is not null && request.Content is null)
            {
                request.Content = _client.CreateContent(body, "application/json");
            }

            using var response = await _client.HttpClient.SendAsync(
                request,
                HttpCompletionOption.ResponseHeadersRead,
                effectiveCancellationToken).ConfigureAwait(false);

            if (!response.IsSuccessStatusCode)
            {
                var responseBody = response.Content is null
                    ? null
                    : await ApiClient.ReadContentAsStringAsync(response.Content, effectiveCancellationToken).ConfigureAwait(false);
                switch ((int)response.StatusCode)
                {
                    case 404:
                    {
                        var errorForStatus404 = _client.TryDeserialize<Error>(responseBody);
                        throw new ApiException<Error>(response.StatusCode, errorForStatus404, responseBody, response.RequestMessage?.RequestUri);
                    }
                    case 409:
                    {
                        var errorForStatus409 = _client.TryDeserialize<Error>(responseBody);
                        throw new ApiException<Error>(response.StatusCode, errorForStatus409, responseBody, response.RequestMessage?.RequestUri);
                    }
                }
                var fallbackError = _client.TryDeserialize<ApiError>(responseBody);
                throw new ApiException(response.StatusCode, fallbackError, responseBody, response.RequestMessage?.RequestUri);
            }
            return ApiResponse<JsonDocument>.From(default, response.StatusCode, response.Headers, response.RequestMessage?.RequestUri);
        }
        finally
        {
            timeoutScope?.Dispose();
        }
    }
}