// <auto-generated />
#nullable enable

namespace SumUp;

/// <summary>
/// Optional parameters for List checkouts.
/// </summary>
public sealed partial class CheckoutsListOptions
{
    /// <summary>Filters the list of checkout resources by the unique ID of the checkout.</summary>
    public string? CheckoutReference { get; set; }
}