// <auto-generated />
#nullable enable

namespace SumUp;
using System.Collections.Generic;

/// <summary>
/// Optional parameters for List memberships.
/// </summary>
public sealed partial class MembershipsListOptions
{
    /// <summary>Offset of the first member to return.</summary>
    public int? Offset { get; set; }
    /// <summary>Maximum number of members to return.</summary>
    public int? Limit { get; set; }
    /// <summary>Filter memberships by resource kind.</summary>
    public string? Kind { get; set; }
    /// <summary>Filter the returned memberships by the membership status.</summary>
    public MembershipStatus? Status { get; set; }
    /// <summary>Filter memberships by resource kind.</summary>
    public string? ResourceType { get; set; }
    /// <summary>Filter memberships by the sandbox status of the resource the membership is in.</summary>
    public bool? ResourceAttributesSandbox { get; set; }
    /// <summary>Filter memberships by the name of the resource the membership is in.</summary>
    public string? ResourceName { get; set; }
    /// <summary>Filter memberships by the ID of the resource the membership is in.</summary>
    public string? ResourceId { get; set; }
    /// <summary>Filter memberships by the parent of the resource the membership is in. Omit both resource.parent.id and resource.parent.type to skip parent filtering. When filtering by parent, both parameters must be present. To select resources without a parent, set each parameter to an empty value. Otherwise, both parameters must identify a parent.</summary>
    public string? ResourceParentId { get; set; }
    /// <summary>Filter memberships by the parent of the resource the membership is in. Omit both resource.parent.id and resource.parent.type to skip parent filtering. When filtering by parent, both parameters must be present. To select resources without a parent, set each parameter to an empty value. Otherwise, both parameters must identify a parent.</summary>
    public string? ResourceParentType { get; set; }
    /// <summary>Filter the returned memberships by role.</summary>
    public IEnumerable<string>? Roles { get; set; }
}