// <auto-generated />
#nullable enable

namespace SumUp;

/// <summary>
/// Optional parameters for Retrieve a Merchant.
/// </summary>
public sealed partial class MerchantsGetOptions
{
    /// <summary>The version of the resource. At the moment, the only supported value is latest. When provided and the requested resource's change_status is pending, the resource will be returned with all pending changes applied. When no changes are pending the resource is returned as is. The change_status in the response body will reflect the current state of the resource.</summary>
    public string? Version { get; set; }
}