// <auto-generated />
#nullable enable

namespace SumUp;

/// <summary>
/// Optional parameters for List payouts.
/// </summary>
public sealed partial class PayoutsListOptions
{
    /// <summary>Start date of the payout period filter, inclusive, in ISO8601 date format (YYYY-MM-DD).</summary>
    public DateOnly StartDate { get; set; }
    /// <summary>End date of the payout period filter, inclusive, in ISO8601 date format (YYYY-MM-DD). Must be greater than or equal to start_date.</summary>
    public DateOnly EndDate { get; set; }
    /// <summary>Response format for the payout list.</summary>
    public string? Format { get; set; }
    /// <summary>Maximum number of payout records to return.</summary>
    public int? Limit { get; set; }
    /// <summary>Sort direction for the returned payouts.</summary>
    public string? Order { get; set; }
}