// <auto-generated />
#nullable enable

namespace SumUp;

/// <summary>
/// Optional parameters for Create a Go Reader Payment.
/// </summary>
public sealed partial class ReadersCreateGoCheckoutOptions
{
    /// <summary>Access token in the format 'Bearer {token}'.</summary>
    public string Authorization { get; set; } = default!;
}