// <auto-generated />
#nullable enable

namespace SumUp;

/// <summary>
/// Optional parameters for Retrieve receipt details.
/// </summary>
public sealed partial class ReceiptsGetOptions
{
    /// <summary>Short unique identifier for the merchant.</summary>
    public string Mid { get; set; } = default!;
    /// <summary>Unique identifier of the transaction event to include on the receipt.</summary>
    public int? TxEventId { get; set; }
}