// <auto-generated />
#nullable enable

namespace SumUp;

/// <summary>
/// Optional parameters for Retrieve receipt details.
/// </summary>
public sealed partial class ReceiptsGetOptions
{
    /// <summary>Merchant code.</summary>
    public string Mid { get; set; } = default!;
    /// <summary>The ID of the transaction event (refund).</summary>
    public int? TxEventId { get; set; }
}