// <auto-generated />
#nullable enable

namespace SumUp;

/// <summary>
/// Optional parameters for List operators.
/// </summary>
public sealed partial class SubaccountsListSubAccountsOptions
{
    /// <summary>Search query used to filter users that match given query term. Current implementation allow querying only over the email address. All operators whos email address contains the query string are returned.</summary>
    public string? Query { get; set; }
    /// <summary>If true the list of operators will include also the primary user.</summary>
    public bool? IncludePrimary { get; set; }
}