// <auto-generated />
#nullable enable

namespace SumUp;

/// <summary>
/// Optional parameters for Retrieve a transaction.
/// </summary>
public sealed partial class TransactionsGetOptions
{
    /// <summary>Retrieves the transaction resource with the specified transaction ID (the id parameter in the transaction resource).</summary>
    public string? Id { get; set; }
    /// <summary>Retrieves the transaction resource with the specified transaction code.</summary>
    public string? TransactionCode { get; set; }
    /// <summary>External/foreign transaction id (passed by clients).</summary>
    public string? ForeignTransactionId { get; set; }
    /// <summary>Client transaction id.</summary>
    public string? ClientTransactionId { get; set; }
}