// <auto-generated />
#nullable enable

namespace SumUp;

/// <summary>
/// Optional parameters for Retrieve a transaction.
/// </summary>
public sealed partial class TransactionsGetOptions
{
    /// <summary>Retrieves the transaction resource with the specified transaction ID (the id parameter in the transaction resource).</summary>
    public string? Id { get; set; }
    /// <summary>Retrieves the transaction resource with the specified transaction code.</summary>
    public string? TransactionCode { get; set; }
    /// <summary>External transaction identifier supplied by the client.</summary>
    public string? ForeignTransactionId { get; set; }
    /// <summary>Client-supplied identifier of the transaction.</summary>
    public string? ClientTransactionId { get; set; }
}