// <auto-generated />
#nullable enable

namespace SumUp;
using System.Collections.Generic;

/// <summary>
/// Optional parameters for List transactions.
/// </summary>
public sealed partial class TransactionsListOptions
{
    /// <summary>Retrieves the transaction resource with the specified transaction code.</summary>
    public string? TransactionCode { get; set; }
    /// <summary>Specifies the order in which the returned results are displayed.</summary>
    public string? Order { get; set; }
    /// <summary>Specifies the maximum number of results per page. Value must be a positive integer and if not specified, will return 10 results.</summary>
    public int? Limit { get; set; }
    /// <summary>Filters the returned results by user email.</summary>
    public IEnumerable<string>? Users { get; set; }
    /// <summary>Filters the returned results by the specified list of final statuses of the transactions.</summary>
    public IEnumerable<string>? Statuses { get; set; }
    /// <summary>Filters the returned results by the specified list of payment types used for the transactions.</summary>
    public IEnumerable<PaymentType>? PaymentTypes { get; set; }
    /// <summary>Filters the returned results by the specified list of entry modes.</summary>
    public IEnumerable<EntryMode>? EntryModes { get; set; }
    /// <summary>Filters the returned results by the specified list of transaction types.</summary>
    public IEnumerable<string>? Types { get; set; }
    /// <summary>Filters the results by the latest modification time of resources and returns only transactions that are modified *at or after* the specified timestamp (in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) format).</summary>
    public DateTimeOffset? ChangesSince { get; set; }
    /// <summary>Filters the results by the creation time of resources and returns only transactions that are created *before* the specified timestamp (in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) format).</summary>
    public DateTimeOffset? NewestTime { get; set; }
    /// <summary>Filters the results by the reference ID of transaction events and returns only transactions with events whose IDs are *smaller* than the specified value. This parameters supersedes the `newest_time` parameter (if both are provided in the request).</summary>
    public string? NewestRef { get; set; }
    /// <summary>Filters the results by the creation time of resources and returns only transactions that are created *at or after* the specified timestamp (in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) format).</summary>
    public DateTimeOffset? OldestTime { get; set; }
    /// <summary>Filters the results by the reference ID of transaction events and returns only transactions with events whose IDs are *greater* than the specified value. This parameters supersedes the `oldest_time` parameter (if both are provided in the request).</summary>
    public string? OldestRef { get; set; }
}