// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
/// <summary>Details of the registered address.</summary>
public sealed partial class AddressWithDetails
{
    /// <summary>Address line 1</summary>
    [JsonPropertyName("address_line1")]
    public string? AddressLine1 { get; set; }
    /// <summary>Address line 2</summary>
    [JsonPropertyName("address_line2")]
    public string? AddressLine2 { get; set; }
    /// <summary>City</summary>
    [JsonPropertyName("city")]
    public string? City { get; set; }
    /// <summary>undefined</summary>
    [JsonPropertyName("company")]
    public string? Company { get; set; }
    /// <summary>Country ISO 3166-1 code</summary>
    [JsonPropertyName("country")]
    public string? Country { get; set; }
    /// <summary>Country Details</summary>
    [JsonPropertyName("country_details")]
    public CountryDetails? CountryDetails { get; set; }
    /// <summary>undefined</summary>
    [JsonPropertyName("first_name")]
    public string? FirstName { get; set; }
    /// <summary>Landline number</summary>
    [JsonPropertyName("landline")]
    public string? Landline { get; set; }
    /// <summary>undefined</summary>
    [JsonPropertyName("last_name")]
    public string? LastName { get; set; }
    /// <summary>Postal code</summary>
    [JsonPropertyName("post_code")]
    public string? PostCode { get; set; }
    /// <summary>Region code</summary>
    [JsonPropertyName("region_code")]
    public string? RegionCode { get; set; }
    /// <summary>Country region id</summary>
    [JsonPropertyName("region_id")]
    public decimal? RegionId { get; set; }
    /// <summary>Region name</summary>
    [JsonPropertyName("region_name")]
    public string? RegionName { get; set; }
    /// <summary>undefined</summary>
    [JsonPropertyName("state_id")]
    public string? StateId { get; set; }
    /// <summary>TimeOffset Details</summary>
    [JsonPropertyName("timeoffset_details")]
    public TimeoffsetDetails? TimeoffsetDetails { get; set; }
}