// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
/// <summary>Personal address</summary>
public sealed partial class AddressPayloadLegacy
{
    /// <summary>Address line 1</summary>
    [JsonPropertyName("address_line1")]
    public string AddressLine1 { get; set; } = default!;
    /// <summary>Address line 2</summary>
    [JsonPropertyName("address_line2")]
    public string? AddressLine2 { get; set; }
    /// <summary>City</summary>
    [JsonPropertyName("city")]
    public string City { get; set; } = default!;
    /// <summary>Company name</summary>
    [JsonPropertyName("company")]
    public string? Company { get; set; }
    /// <summary>Country ISO 3166-1 code</summary>
    [JsonPropertyName("country")]
    public string Country { get; set; } = default!;
    /// <summary>First name</summary>
    [JsonPropertyName("first_name")]
    public string? FirstName { get; set; }
    /// <summary>Landline number</summary>
    [JsonPropertyName("landline")]
    public string? Landline { get; set; }
    /// <summary>Last name</summary>
    [JsonPropertyName("last_name")]
    public string? LastName { get; set; }
    /// <summary>Postal code</summary>
    [JsonPropertyName("post_code")]
    public string PostCode { get; set; } = default!;
    /// <summary>Country region id</summary>
    [JsonPropertyName("region_id")]
    public decimal? RegionId { get; set; }
    /// <summary>Country region name</summary>
    [JsonPropertyName("region_name")]
    public string? RegionName { get; set; }
}