// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
using System.Collections.Generic;
/// <summary>An address somewhere in the world. The address fields used depend on the country conventions. For example, in Great Britain, `city` is `post_town`. In the United States, the top-level administrative unit used in addresses is `state`, whereas in Chile it's `region`. Whether an address is valid or not depends on whether the locally required fields are present. Fields not supported in a country will be ignored.</summary>
public sealed partial class Address
{
    /// <summary>In Spain, an autonomous community is the first sub-national level of political and administrative division.</summary>
    [JsonPropertyName("autonomous_community")]
    public string? AutonomousCommunity { get; set; }
    /// <summary>The city of the address.</summary>
    [JsonPropertyName("city")]
    public string? City { get; set; }
    /// <summary>In many countries, terms cognate with "commune" are used, referring to the community living in the area and the common interest. Used in countries such as Chile.</summary>
    [JsonPropertyName("commune")]
    public string? Commune { get; set; }
    /// <summary>An [ISO3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) country code. This definition users `oneOf` with a two-character string type to allow for support of future countries in client code.</summary>
    [JsonPropertyName("country")]
    public string Country { get; set; } = default!;
    /// <summary>A county is a geographic region of a country used for administrative or other purposes in some nations. Used in countries such as Ireland, Romania, etc.</summary>
    [JsonPropertyName("county")]
    public string? County { get; set; }
    /// <summary>A department (French: département, Spanish: departamento) is an administrative or political division in several countries. Used in countries such as Colombia.</summary>
    [JsonPropertyName("department")]
    public string? Department { get; set; }
    /// <summary>A district is a type of administrative division that in some countries is managed by the local government. Used in countries such as Portugal.</summary>
    [JsonPropertyName("district")]
    public string? District { get; set; }
    /// <summary>A postal address in Ireland.</summary>
    [JsonPropertyName("eircode")]
    public string? Eircode { get; set; }
    /// <summary>A municipality is usually a single administrative division having corporate status and powers of self-government or jurisdiction as granted by national and regional laws to which it is subordinate. Used in countries such as Colombia.</summary>
    [JsonPropertyName("municipality")]
    public string? Municipality { get; set; }
    /// <summary>Locality level of the address. Used in countries such as Brazil or Chile.</summary>
    [JsonPropertyName("neighborhood")]
    public string? Neighborhood { get; set; }
    /// <summary>The postal code (aka. zip code) of the address.</summary>
    [JsonPropertyName("post_code")]
    public string? PostCode { get; set; }
    /// <summary>A post town is a required part of all postal addresses in the United Kingdom and Ireland, and a basic unit of the postal delivery system.</summary>
    [JsonPropertyName("post_town")]
    public string? PostTown { get; set; }
    /// <summary>The province where the address is located. This may not be relevant in some countries.</summary>
    [JsonPropertyName("province")]
    public string? Province { get; set; }
    /// <summary>The region where the address is located. This may not be relevant in some countries.</summary>
    [JsonPropertyName("region")]
    public string? Region { get; set; }
    /// <summary>Most often, a country has a single state, with various administrative divisions. The term "state" is sometimes used to refer to the federated polities that make up the federation. Used in countries such as the United States and Brazil.</summary>
    [JsonPropertyName("state")]
    public string? State { get; set; }
    [JsonPropertyName("street_address")]
    public IEnumerable<string>? StreetAddress { get; set; }
    /// <summary>A US system of postal codes used by the United States Postal Service (USPS).</summary>
    [JsonPropertyName("zip_code")]
    public string? ZipCode { get; set; }
}