// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
using System.Collections.Generic;
/// <summary>Mobile app settings</summary>
public sealed partial class AppSettings
{
    /// <summary>Advanced mode.</summary>
    [JsonPropertyName("advanced_mode")]
    public string? AdvancedMode { get; set; }
    /// <summary>Barcode scanner.</summary>
    [JsonPropertyName("barcode_scanner")]
    public string? BarcodeScanner { get; set; }
    /// <summary>Cash payment.</summary>
    [JsonPropertyName("cash_payment")]
    public string? CashPayment { get; set; }
    /// <summary>Checkout preference</summary>
    [JsonPropertyName("checkout_preference")]
    public string? CheckoutPreference { get; set; }
    /// <summary>Expected max transaction amount.</summary>
    [JsonPropertyName("expected_max_transaction_amount")]
    public decimal? ExpectedMaxTransactionAmount { get; set; }
    /// <summary>Include vat.</summary>
    [JsonPropertyName("include_vat")]
    public bool? IncludeVat { get; set; }
    /// <summary>Manual entry.</summary>
    [JsonPropertyName("manual_entry")]
    public string? ManualEntry { get; set; }
    /// <summary>Manual entry tutorial.</summary>
    [JsonPropertyName("manual_entry_tutorial")]
    public bool? ManualEntryTutorial { get; set; }
    /// <summary>Mobile payment.</summary>
    [JsonPropertyName("mobile_payment")]
    public string? MobilePayment { get; set; }
    /// <summary>Mobile payment tutorial.</summary>
    [JsonPropertyName("mobile_payment_tutorial")]
    public bool? MobilePaymentTutorial { get; set; }
    /// <summary>Reader payment.</summary>
    [JsonPropertyName("reader_payment")]
    public string? ReaderPayment { get; set; }
    /// <summary>Referral.</summary>
    [JsonPropertyName("referral")]
    public string? Referral { get; set; }
    /// <summary>Tax enabled.</summary>
    [JsonPropertyName("tax_enabled")]
    public bool? TaxEnabled { get; set; }
    /// <summary>Terminal mode tutorial.</summary>
    [JsonPropertyName("terminal_mode_tutorial")]
    public bool? TerminalModeTutorial { get; set; }
    /// <summary>Tip rates.</summary>
    [JsonPropertyName("tip_rates")]
    public IEnumerable<float>? TipRates { get; set; }
    /// <summary>Tipping.</summary>
    [JsonPropertyName("tipping")]
    public string? Tipping { get; set; }
}