// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
public sealed partial class BadGatewayErrors
{
    /// <summary>Fuller message giving context to error</summary>
    [JsonPropertyName("detail")]
    public string Detail { get; set; } = default!;
}