// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
public sealed partial class BankAccountPayload
{
    /// <summary>Determines if this bank account is business or personal.</summary>
    [JsonPropertyName("account_category")]
    public string? AccountCategory { get; set; }
    /// <summary>Account holder name</summary>
    [JsonPropertyName("account_holder_name")]
    public string AccountHolderName { get; set; } = default!;
    /// <summary>Account number</summary>
    [JsonPropertyName("account_number")]
    public string? AccountNumber { get; set; }
    /// <summary>Type of the account.</summary>
    [JsonPropertyName("account_type")]
    public string? AccountType { get; set; }
    /// <summary>Bank code</summary>
    [JsonPropertyName("bank_code")]
    public string? BankCode { get; set; }
    /// <summary>Branch code</summary>
    [JsonPropertyName("branch_code")]
    public string? BranchCode { get; set; }
    /// <summary>Check digit</summary>
    [JsonPropertyName("check_digit")]
    public string? CheckDigit { get; set; }
    /// <summary>IBAN</summary>
    [JsonPropertyName("iban")]
    public string Iban { get; set; } = default!;
    /// <summary>Determines if this bank account will be primary. Default is false</summary>
    [JsonPropertyName("primary")]
    public bool? Primary { get; set; }
    /// <summary>Determines the bank account status.</summary>
    [JsonPropertyName("status")]
    public string? Status { get; set; }
    /// <summary>SWIFT code</summary>
    [JsonPropertyName("swift")]
    public string Swift { get; set; } = default!;
}