// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
public sealed partial class BankAccount
{
    /// <summary>Account category - business or personal</summary>
    [JsonPropertyName("account_category")]
    public string? AccountCategory { get; set; }
    [JsonPropertyName("account_holder_name")]
    public string? AccountHolderName { get; set; }
    /// <summary>Account number</summary>
    [JsonPropertyName("account_number")]
    public string? AccountNumber { get; set; }
    /// <summary>Type of the account</summary>
    [JsonPropertyName("account_type")]
    public string? AccountType { get; set; }
    /// <summary>Bank code</summary>
    [JsonPropertyName("bank_code")]
    public string? BankCode { get; set; }
    /// <summary>Bank name</summary>
    [JsonPropertyName("bank_name")]
    public string? BankName { get; set; }
    /// <summary>Branch code</summary>
    [JsonPropertyName("branch_code")]
    public string? BranchCode { get; set; }
    /// <summary>Creation date of the bank account</summary>
    [JsonPropertyName("created_at")]
    public string? CreatedAt { get; set; }
    /// <summary>IBAN</summary>
    [JsonPropertyName("iban")]
    public string? Iban { get; set; }
    /// <summary>The primary bank account is the one used for payouts</summary>
    [JsonPropertyName("primary")]
    public bool? Primary { get; set; }
    /// <summary>Status in the verification process</summary>
    [JsonPropertyName("status")]
    public string? Status { get; set; }
    /// <summary>SWIFT code</summary>
    [JsonPropertyName("swift")]
    public string? Swift { get; set; }
}