// <auto-generated />
#nullable enable

namespace SumUp;

using System.Runtime.Serialization;
using System.Text.Json.Serialization;

[JsonConverter(typeof(EnumMemberJsonConverterFactory))]
public enum BankAccountPayloadAccountCategory
{
    [EnumMember(Value = "PERSONAL")]
    Personal,
    [EnumMember(Value = "BUSINESS")]
    Business,
}