// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
public sealed partial class BaseError
{
    /// <summary>A unique identifier for the error instance. This can be used to trace the error back to the server logs.</summary>
    [JsonPropertyName("instance")]
    public string? Instance { get; set; }
    /// <summary>A human-readable message describing the error that occurred.</summary>
    [JsonPropertyName("message")]
    public string? Message { get; set; }
}