// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
public sealed partial class BusinessOwnersItem
{
    /// <summary>Date of birth</summary>
    [JsonPropertyName("date_of_birth")]
    public string? DateOfBirth { get; set; }
    /// <summary>BO's first name</summary>
    [JsonPropertyName("first_name")]
    public string? FirstName { get; set; }
    /// <summary>BO's Landline</summary>
    [JsonPropertyName("landline")]
    public string? Landline { get; set; }
    /// <summary>BO's last name of the user</summary>
    [JsonPropertyName("last_name")]
    public string? LastName { get; set; }
    /// <summary>Mobile phone number</summary>
    [JsonPropertyName("mobile_phone")]
    public string? MobilePhone { get; set; }
    /// <summary>Ownership percentage</summary>
    [JsonPropertyName("ownership")]
    public decimal? Ownership { get; set; }
}