// <auto-generated />
#nullable enable

namespace SumUp;

using System.Runtime.Serialization;
using System.Text.Json.Serialization;

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum CardType
{
    [EnumMember(Value = "AMEX")]
    Amex,
    [EnumMember(Value = "CUP")]
    Cup,
    [EnumMember(Value = "DINERS")]
    Diners,
    [EnumMember(Value = "DISCOVER")]
    Discover,
    [EnumMember(Value = "ELO")]
    Elo,
    [EnumMember(Value = "ELV")]
    Elv,
    [EnumMember(Value = "HIPERCARD")]
    Hipercard,
    [EnumMember(Value = "JCB")]
    Jcb,
    [EnumMember(Value = "MAESTRO")]
    Maestro,
    [EnumMember(Value = "MASTERCARD")]
    Mastercard,
    [EnumMember(Value = "VISA")]
    Visa,
    [EnumMember(Value = "VISA_ELECTRON")]
    VisaElectron,
    [EnumMember(Value = "VISA_VPAY")]
    VisaVpay,
    [EnumMember(Value = "UNKNOWN")]
    Unknown,
}