// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
/// <summary>__Required when payment type is `card`.__ Details of the payment card.</summary>
public sealed partial class Card
{
    /// <summary>Three or four-digit card verification value (security code) of the payment card.</summary>
    [JsonPropertyName("cvv")]
    public string Cvv { get; set; } = default!;
    /// <summary>Month from the expiration time of the payment card. Accepted format is `MM`.</summary>
    [JsonPropertyName("expiry_month")]
    public string ExpiryMonth { get; set; } = default!;
    /// <summary>Year from the expiration time of the payment card. Accepted formats are `YY` and `YYYY`.</summary>
    [JsonPropertyName("expiry_year")]
    public string ExpiryYear { get; set; } = default!;
    /// <summary>Last 4 digits of the payment card number.</summary>
    [JsonPropertyName("last_4_digits")]
    public string Last4Digits { get; set; } = default!;
    /// <summary>Name of the cardholder as it appears on the payment card.</summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = default!;
    /// <summary>Number of the payment card (without spaces).</summary>
    [JsonPropertyName("number")]
    public string Number { get; set; } = default!;
    /// <summary>Issuing card network of the payment card used for the transaction.</summary>
    [JsonPropertyName("type")]
    public CardType Type { get; set; }
    /// <summary>Required five-digit ZIP code. Applicable only to merchant users in the USA.</summary>
    [JsonPropertyName("zip_code")]
    public string? ZipCode { get; set; }
}