// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
using System.Collections.Generic;
/// <summary>Details of the payment checkout.</summary>
public sealed partial class CheckoutCreateRequest
{
    /// <summary>Amount of the payment.</summary>
    [JsonPropertyName("amount")]
    public float Amount { get; set; }
    /// <summary>Unique ID of the payment checkout specified by the client application when creating the checkout resource.</summary>
    [JsonPropertyName("checkout_reference")]
    public string CheckoutReference { get; set; } = default!;
    /// <summary>Three-letter [ISO4217](https://en.wikipedia.org/wiki/ISO_4217) code of the currency for the amount. Currently supported currency values are enumerated above.</summary>
    [JsonPropertyName("currency")]
    public Currency Currency { get; set; }
    /// <summary>Unique identification of a customer. If specified, the checkout session and payment instrument are associated with the referenced customer.</summary>
    [JsonPropertyName("customer_id")]
    public string? CustomerId { get; set; }
    /// <summary>Date and time of the creation of the payment checkout. Response format expressed according to [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) code.</summary>
    [JsonPropertyName("date")]
    public DateTimeOffset? Date { get; }
    /// <summary>Short description of the checkout visible in the SumUp dashboard. The description can contribute to reporting, allowing easier identification of a checkout.</summary>
    [JsonPropertyName("description")]
    public string? Description { get; set; }
    /// <summary>Unique ID of the checkout resource.</summary>
    [JsonPropertyName("id")]
    public string? Id { get; }
    /// <summary>Unique identifying code of the merchant profile.</summary>
    [JsonPropertyName("merchant_code")]
    public string MerchantCode { get; set; } = default!;
    /// <summary>Purpose of the checkout.</summary>
    [JsonPropertyName("purpose")]
    public string? Purpose { get; set; }
    /// <summary>__Required__ for [APMs](https://developer.sumup.com/online-payments/apm/introduction) and __recommended__ for card payments. Refers to a url where the end user is redirected once the payment processing completes. If not specified, the [Payment Widget](https://developer.sumup.com/online-payments/tools/card-widget) renders [3DS challenge](https://developer.sumup.com/online-payments/features/3ds) within an iframe instead of performing a full-page redirect.</summary>
    [JsonPropertyName("redirect_url")]
    public string? RedirectUrl { get; set; }
    /// <summary>URL to which the SumUp platform sends the processing status of the payment checkout.</summary>
    [JsonPropertyName("return_url")]
    public string? ReturnUrl { get; set; }
    /// <summary>Current status of the checkout.</summary>
    [JsonPropertyName("status")]
    public string? Status { get; }
    /// <summary>List of transactions related to the payment.</summary>
    [JsonPropertyName("transactions")]
    public IEnumerable<CheckoutCreateRequestTransactionsItem>? Transactions { get; }
    /// <summary>Date and time of the checkout expiration before which the client application needs to send a processing request. If no value is present, the checkout does not have an expiration time.</summary>
    [JsonPropertyName("valid_until")]
    public DateTimeOffset? ValidUntil { get; set; }
}