// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
/// <summary>Request body for updating an existing checkout. Include only the fields that should be changed.</summary>
public sealed partial class CheckoutUpdateRequest
{
    /// <summary>Updated amount to be charged to the payer, expressed in major units.</summary>
    [JsonPropertyName("amount")]
    public float? Amount { get; set; }
    /// <summary>Updated merchant-defined reference for the checkout.</summary>
    [JsonPropertyName("checkout_reference")]
    public string? CheckoutReference { get; set; }
    /// <summary>Three-letter ISO4217 code of the currency for the amount. Currently supported currency values are enumerated above.</summary>
    [JsonPropertyName("currency")]
    public Currency? Currency { get; set; }
    /// <summary>Updated merchant-scoped customer identifier associated with the checkout.</summary>
    [JsonPropertyName("customer_id")]
    public string? CustomerId { get; set; }
    /// <summary>Updated short merchant-defined description shown in SumUp tools and reporting.</summary>
    [JsonPropertyName("description")]
    public string? Description { get; set; }
    /// <summary>Updated expiration timestamp. The checkout must be processed before this moment, otherwise it becomes unusable.</summary>
    [JsonPropertyName("valid_until")]
    public DateTimeOffset? ValidUntil { get; set; }
}