// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
using System.Collections.Generic;
/// <summary>Checkout resource returned after a synchronous processing attempt. In addition to the base checkout fields, it can include the resulting transaction identifiers and any newly created payment instrument token.</summary>
public sealed partial class CheckoutSuccess
{
    /// <summary>Amount to be charged to the payer, expressed in major units.</summary>
    [JsonPropertyName("amount")]
    public float? Amount { get; set; }
    /// <summary>Merchant-defined reference for the checkout. Use it to correlate the SumUp checkout with your own order, cart, subscription, or payment attempt in your systems.</summary>
    [JsonPropertyName("checkout_reference")]
    public string? CheckoutReference { get; set; }
    /// <summary>Three-letter ISO4217 code of the currency for the amount. Currently supported currency values are enumerated above.</summary>
    [JsonPropertyName("currency")]
    public Currency? Currency { get; set; }
    /// <summary>Merchant-scoped identifier of the customer associated with the checkout. Use it when storing payment instruments or reusing saved customer context for recurring and returning-payer flows.</summary>
    [JsonPropertyName("customer_id")]
    public string? CustomerId { get; set; }
    /// <summary>Date and time of the creation of the payment checkout. Response format expressed according to ISO8601 code.</summary>
    [JsonPropertyName("date")]
    public DateTimeOffset? Date { get; set; }
    /// <summary>Short merchant-defined description shown in SumUp tools and reporting. Use it to make the checkout easier to recognize in dashboards, support workflows, and reconciliation.</summary>
    [JsonPropertyName("description")]
    public string? Description { get; set; }
    /// <summary>Unique SumUp identifier of the checkout resource.</summary>
    [JsonPropertyName("id")]
    [JsonInclude]
    public string? Id { get; private set; }
    /// <summary>Details of the mandate linked to the saved payment instrument.</summary>
    [JsonPropertyName("mandate")]
    public MandateResponse? Mandate { get; set; }
    /// <summary>Merchant account that receives the payment.</summary>
    [JsonPropertyName("merchant_code")]
    public string? MerchantCode { get; set; }
    /// <summary>Name of the merchant</summary>
    [JsonPropertyName("merchant_name")]
    public string? MerchantName { get; set; }
    /// <summary>Details of the saved payment instrument created or reused during checkout processing.</summary>
    [JsonPropertyName("payment_instrument")]
    public CheckoutSuccessPaymentInstrument? PaymentInstrument { get; set; }
    /// <summary>URL where the payer is redirected after a redirect-based payment or SCA flow completes.</summary>
    [JsonPropertyName("redirect_url")]
    public string? RedirectUrl { get; set; }
    /// <summary>Optional backend callback URL used by SumUp to notify your platform about processing updates for the checkout.</summary>
    [JsonPropertyName("return_url")]
    public string? ReturnUrl { get; set; }
    /// <summary>Current high-level state of the checkout. PENDING means the checkout exists but is not yet completed, PAID means a payment succeeded, FAILED means the latest processing attempt failed, and EXPIRED means the checkout can no longer be processed.</summary>
    [JsonPropertyName("status")]
    public CheckoutSuccessStatus? Status { get; set; }
    /// <summary>Transaction code of the successful transaction with which the payment for the checkout is completed.</summary>
    [JsonPropertyName("transaction_code")]
    [JsonInclude]
    public string? TransactionCode { get; private set; }
    /// <summary>Transaction ID of the successful transaction with which the payment for the checkout is completed.</summary>
    [JsonPropertyName("transaction_id")]
    [JsonInclude]
    public string? TransactionId { get; private set; }
    /// <summary>Payment attempts and resulting transaction records linked to this checkout. Use the Transactions endpoints when you need the authoritative payment result and event history.</summary>
    [JsonPropertyName("transactions")]
    public IEnumerable<CheckoutSuccessTransactionsItem>? Transactions { get; set; }
    /// <summary>Optional expiration timestamp. The checkout must be processed before this moment, otherwise it becomes unusable. If omitted, the checkout does not have an explicit expiry time.</summary>
    [JsonPropertyName("valid_until")]
    public DateTimeOffset? ValidUntil { get; set; }
}