// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
/// <summary>3DS Response</summary>
public sealed partial class CheckoutAccepted
{
    /// <summary>Required action processing 3D Secure payments.</summary>
    [JsonPropertyName("next_step")]
    public CheckoutAcceptedNextStep? NextStep { get; set; }
}