// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
using System.Collections.Generic;
/// <summary>Required action processing 3D Secure payments.</summary>
public sealed partial class CheckoutAcceptedNextStep
{
    /// <summary>Indicates allowed mechanisms for redirecting an end user. If both values are provided to ensure a redirect takes place in either.</summary>
    [JsonPropertyName("mechanism")]
    public IEnumerable<string>? Mechanism { get; set; }
    /// <summary>Method used to complete the redirect.</summary>
    [JsonPropertyName("method")]
    public string? Method { get; set; }
    /// <summary>Contains parameters essential for form redirection. Number of object keys and their content can vary.</summary>
    [JsonPropertyName("payload")]
    public CheckoutAcceptedNextStepPayload? Payload { get; set; }
    /// <summary>Refers to a url where the end user is redirected once the payment processing completes.</summary>
    [JsonPropertyName("redirect_url")]
    public string? RedirectUrl { get; set; }
    /// <summary>Where the end user is redirected.</summary>
    [JsonPropertyName("url")]
    public string? Url { get; set; }
}