// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
public sealed partial class CheckoutCreateRequestTransactionsItem
{
    /// <summary>Total amount of the transaction.</summary>
    [JsonPropertyName("amount")]
    public float? Amount { get; set; }
    /// <summary>Authorization code for the transaction sent by the payment card issuer or bank. Applicable only to card payments.</summary>
    [JsonPropertyName("auth_code")]
    public string? AuthCode { get; set; }
    /// <summary>Three-letter [ISO4217](https://en.wikipedia.org/wiki/ISO_4217) code of the currency for the amount. Currently supported currency values are enumerated above.</summary>
    [JsonPropertyName("currency")]
    public Currency? Currency { get; set; }
    /// <summary>Entry mode of the payment details.</summary>
    [JsonPropertyName("entry_mode")]
    public EntryMode? EntryMode { get; set; }
    /// <summary>Unique ID of the transaction.</summary>
    [JsonPropertyName("id")]
    public string? Id { get; set; }
    /// <summary>Current number of the installment for deferred payments.</summary>
    [JsonPropertyName("installments_count")]
    public int? InstallmentsCount { get; set; }
    /// <summary>Internal unique ID of the transaction on the SumUp platform.</summary>
    [JsonPropertyName("internal_id")]
    public long? InternalId { get; set; }
    /// <summary>Unique code of the registered merchant to whom the payment is made.</summary>
    [JsonPropertyName("merchant_code")]
    public string? MerchantCode { get; set; }
    /// <summary>Payment type used for the transaction.</summary>
    [JsonPropertyName("payment_type")]
    public PaymentType? PaymentType { get; set; }
    /// <summary>Current status of the transaction.</summary>
    [JsonPropertyName("status")]
    public string? Status { get; set; }
    /// <summary>Date and time of the creation of the transaction. Response format expressed according to [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) code.</summary>
    [JsonPropertyName("timestamp")]
    public DateTimeOffset? Timestamp { get; set; }
    /// <summary>Amount of the tip (out of the total transaction amount).</summary>
    [JsonPropertyName("tip_amount")]
    public float? TipAmount { get; set; }
    /// <summary>Transaction code returned by the acquirer/processing entity after processing the transaction.</summary>
    [JsonPropertyName("transaction_code")]
    public string? TransactionCode { get; set; }
    /// <summary>Amount of the applicable VAT (out of the total transaction amount).</summary>
    [JsonPropertyName("vat_amount")]
    public float? VatAmount { get; set; }
}