// <auto-generated />
#nullable enable

namespace SumUp;

using System.Runtime.Serialization;
using System.Text.Json.Serialization;

[JsonConverter(typeof(EnumMemberJsonConverterFactory))]
public enum CheckoutCreateRequestPurpose
{
    [EnumMember(Value = "CHECKOUT")]
    Checkout,
    [EnumMember(Value = "SETUP_RECURRING_PAYMENT")]
    SetupRecurringPayment,
}