// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
public sealed partial class CheckoutSuccessTransactionsItem
{
    /// <summary>Total amount of the transaction.</summary>
    [JsonPropertyName("amount")]
    public float? Amount { get; set; }
    /// <summary>Authorization code for the transaction sent by the payment card issuer or bank. Applicable only to card payments.</summary>
    [JsonPropertyName("auth_code")]
    public string? AuthCode { get; set; }
    /// <summary>Three-letter ISO 4217 currency code of the amount.</summary>
    [JsonPropertyName("currency")]
    public Currency? Currency { get; set; }
    /// <summary>Entry mode of the payment details.</summary>
    [JsonPropertyName("entry_mode")]
    public EntryMode? EntryMode { get; set; }
    /// <summary>Unique identifier of the transaction.</summary>
    [JsonPropertyName("id")]
    public string? Id { get; set; }
    /// <summary>Number of installments for a deferred payment.</summary>
    [JsonPropertyName("installments_count")]
    public int? InstallmentsCount { get; set; }
    /// <summary>Unique code of the registered merchant to whom the payment is made.</summary>
    [JsonPropertyName("merchant_code")]
    public string? MerchantCode { get; set; }
    /// <summary>Payment type used for the transaction.</summary>
    [JsonPropertyName("payment_type")]
    public PaymentType? PaymentType { get; set; }
    /// <summary>Current status of the transaction. - PENDING: The transaction has been created but its final outcome is not known yet. - SUCCESSFUL: The transaction completed successfully. - CANCELLED: The transaction was cancelled or otherwise reversed before completion. - FAILED: The transaction attempt did not complete successfully. - REFUNDED: The transaction was refunded in full or in part.</summary>
    [JsonPropertyName("status")]
    public TransactionStatus? Status { get; set; }
    /// <summary>The timestamp of when the transaction was created.</summary>
    [JsonPropertyName("timestamp")]
    public DateTimeOffset? Timestamp { get; set; }
    /// <summary>Amount of the tip (out of the total transaction amount).</summary>
    [JsonPropertyName("tip_amount")]
    public float? TipAmount { get; set; }
    /// <summary>Transaction code returned by the acquirer/processing entity after processing the transaction.</summary>
    [JsonPropertyName("transaction_code")]
    public string? TransactionCode { get; set; }
    /// <summary>Amount of the applicable VAT (out of the total transaction amount).</summary>
    [JsonPropertyName("vat_amount")]
    public float? VatAmount { get; set; }
}