// <auto-generated />
#nullable enable

namespace SumUp;

using System.Runtime.Serialization;
using System.Text.Json.Serialization;

[JsonConverter(typeof(EnumMemberJsonConverterFactory))]
public enum CheckoutSuccessStatus
{
    [EnumMember(Value = "PENDING")]
    Pending,
    [EnumMember(Value = "FAILED")]
    Failed,
    [EnumMember(Value = "PAID")]
    Paid,
    [EnumMember(Value = "EXPIRED")]
    Expired,
}