// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
using System.Text.Json;
/// <summary>Contains parameters essential for form redirection. Number of object keys and their content can vary.</summary>
public sealed partial class CheckoutAcceptedNextStepPayload
{
    [JsonPropertyName("MD")]
    public JsonDocument? Md { get; set; }
    [JsonPropertyName("PaReq")]
    public JsonDocument? PaReq { get; set; }
    [JsonPropertyName("TermUrl")]
    public JsonDocument? TermUrl { get; set; }
}