// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
/// <summary>Object containing token information for the specified payment instrument</summary>
public sealed partial class CheckoutSuccessPaymentInstrument
{
    /// <summary>Token value</summary>
    [JsonPropertyName("token")]
    public string? Token { get; set; }
}