// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
using System.Collections.Generic;
/// <summary>Instructions for the next action the payer or client must take.</summary>
public sealed partial class CheckoutAcceptedNextStep
{
    /// <summary>Allowed presentation mechanisms for the next step. `iframe` means the flow can be embedded, while `browser` means it can be completed through a full-page redirect.</summary>
    [JsonPropertyName("mechanism")]
    public IEnumerable<CheckoutAcceptedNextStepMechanismItem>? Mechanism { get; set; }
    /// <summary>HTTP method to use when following the next step.</summary>
    [JsonPropertyName("method")]
    public string? Method { get; set; }
    /// <summary>Parameters required to complete the next step. The exact keys depend on the payment provider and flow type.</summary>
    [JsonPropertyName("payload")]
    public IDictionary<string, string>? Payload { get; set; }
    /// <summary>Merchant URL where the payer returns after the external flow finishes.</summary>
    [JsonPropertyName("redirect_url")]
    public string? RedirectUrl { get; set; }
    /// <summary>URL to open or submit in order to continue processing.</summary>
    [JsonPropertyName("url")]
    public string? Url { get; set; }
}