// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
using System.Collections.Generic;
/// <summary>Information about the company or business. This is legal information that is used for verification.</summary>
public sealed partial class Company
{
    /// <summary>The company's primary address.</summary>
    [JsonPropertyName("address")]
    public Address? Address { get; set; }
    /// <summary>Object attributes that are modifiable only by SumUp applications.</summary>
    [JsonPropertyName("attributes")]
    public Attributes? Attributes { get; set; }
    /// <summary>A list of country-specific company identifiers.</summary>
    [JsonPropertyName("identifiers")]
    public IEnumerable<CompanyIdentifier>? Identifiers { get; set; }
    /// <summary>The category identifying the legal structure of the company or legal entity.</summary>
    [JsonPropertyName("legal_type")]
    public string? LegalType { get; set; }
    /// <summary>The merchant category code for the account as specified by ISO18245. MCCs are used to classify businesses based on the goods or services they provide.</summary>
    [JsonPropertyName("merchant_category_code")]
    public string? MerchantCategoryCode { get; set; }
    /// <summary>The company's legal name.</summary>
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    /// <summary>The company's phone number (used for verification) in E.164 format.</summary>
    [JsonPropertyName("phone_number")]
    public string? PhoneNumber { get; set; }
    /// <summary>A trading address is where your suppliers, banks or customers send you correspondence to. Trading address can be different to the company's registered address (address).</summary>
    [JsonPropertyName("trading_address")]
    public Address? TradingAddress { get; set; }
    /// <summary>HTTP(S) URL of the company's website.</summary>
    [JsonPropertyName("website")]
    public string? Website { get; set; }
}