// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
public sealed partial class CompanyIdentifier
{
    /// <summary>The unique reference for the company identifier type as defined in the country SDK.</summary>
    [JsonPropertyName("ref")]
    public string RefValue { get; set; } = default!;
    /// <summary>The company identifier value.</summary>
    [JsonPropertyName("value")]
    public string Value { get; set; } = default!;
}