// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
/// <summary>Country Details</summary>
public sealed partial class CountryDetails
{
    /// <summary>Currency ISO 4217 code</summary>
    [JsonPropertyName("currency")]
    public string? Currency { get; set; }
    /// <summary>Country EN name</summary>
    [JsonPropertyName("en_name")]
    public string? EnName { get; set; }
    /// <summary>Country ISO code</summary>
    [JsonPropertyName("iso_code")]
    public string? IsoCode { get; set; }
    /// <summary>Country native name</summary>
    [JsonPropertyName("native_name")]
    public string? NativeName { get; set; }
}