// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
using System.Text.Json;
/// <summary>Unprocessable entity</summary>
public sealed partial class CreateReaderCheckoutUnprocessableEntity
{
    [JsonPropertyName("errors")]
    public JsonDocument Errors { get; set; } = default!;
}