// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
public sealed partial class CreateReaderCheckoutErrorErrors
{
    /// <summary>Error message</summary>
    [JsonPropertyName("detail")]
    public string? Detail { get; set; }
    /// <summary>Error code</summary>
    [JsonPropertyName("type")]
    public string Type { get; set; } = default!;
}