// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
using System.Collections.Generic;
/// <summary>Reader Checkout</summary>
public sealed partial class CreateReaderCheckoutRequest
{
    /// <summary>Affiliate metadata for the transaction. It is a field that allow for integrators to track the source of the transaction.</summary>
    [JsonPropertyName("affiliate")]
    public CreateReaderCheckoutRequestAffiliate? Affiliate { get; set; }
    /// <summary>The card type of the card used for the transaction. Is is required only for some countries (e.g: Brazil).</summary>
    [JsonPropertyName("card_type")]
    public string? CardType { get; set; }
    /// <summary>Description of the checkout to be shown in the Merchant Sales</summary>
    [JsonPropertyName("description")]
    public string? Description { get; set; }
    /// <summary>Number of installments for the transaction. It may vary according to the merchant country. For example, in Brazil, the maximum number of installments is 12. Omit if the merchant country does support installments. Otherwise, the checkout will be rejected.</summary>
    [JsonPropertyName("installments")]
    public int? Installments { get; set; }
    /// <summary>Webhook URL to which the payment result will be sent. It must be a HTTPS url.</summary>
    [JsonPropertyName("return_url")]
    public string? ReturnUrl { get; set; }
    /// <summary>List of tipping rates to be displayed to the cardholder. The rates are in percentage and should be between 0.01 and 0.99. The list should be sorted in ascending order.</summary>
    [JsonPropertyName("tip_rates")]
    public IEnumerable<float>? TipRates { get; set; }
    /// <summary>Time in seconds the cardholder has to select a tip rate. If not provided, the default value is 30 seconds. It can only be set if `tip_rates` is provided. **Note**: If the target device is a Solo, it must be in version 3.3.38.0 or higher.</summary>
    [JsonPropertyName("tip_timeout")]
    public int? TipTimeout { get; set; }
    /// <summary>Amount structure. The amount is represented as an integer value altogether with the currency and the minor unit. For example, EUR 1.00 is represented as value 100 with minor unit of 2.</summary>
    [JsonPropertyName("total_amount")]
    public CreateReaderCheckoutRequestTotalAmount TotalAmount { get; set; } = default!;
}