// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
/// <summary>Error description</summary>
public sealed partial class CreateReaderTerminateError
{
    [JsonPropertyName("errors")]
    public CreateReaderTerminateErrorErrors Errors { get; set; } = default!;
}