// <auto-generated />
#nullable enable

namespace SumUp;

using System.Runtime.Serialization;
using System.Text.Json.Serialization;

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum Currency
{
    [EnumMember(Value = "BGN")]
    Bgn,
    [EnumMember(Value = "BRL")]
    Brl,
    [EnumMember(Value = "CHF")]
    Chf,
    [EnumMember(Value = "CLP")]
    Clp,
    [EnumMember(Value = "COP")]
    Cop,
    [EnumMember(Value = "CZK")]
    Czk,
    [EnumMember(Value = "DKK")]
    Dkk,
    [EnumMember(Value = "EUR")]
    Eur,
    [EnumMember(Value = "GBP")]
    Gbp,
    [EnumMember(Value = "HRK")]
    Hrk,
    [EnumMember(Value = "HUF")]
    Huf,
    [EnumMember(Value = "NOK")]
    Nok,
    [EnumMember(Value = "PLN")]
    Pln,
    [EnumMember(Value = "RON")]
    Ron,
    [EnumMember(Value = "SEK")]
    Sek,
    [EnumMember(Value = "USD")]
    Usd,
}