// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
public sealed partial class CustomersUpdateRequest
{
    /// <summary>Personal details for the customer.</summary>
    [JsonPropertyName("personal_details")]
    public PersonalDetails? PersonalDetails { get; set; }
}