// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
public sealed partial class DetailsErrorFailedConstraintsItem
{
    [JsonPropertyName("message")]
    public string? Message { get; set; }
    [JsonPropertyName("reference")]
    public string? Reference { get; set; }
}