// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
using System.Collections.Generic;
using System.Text.Json;
using System.Text;
/// <summary>Error message structure.</summary>
public sealed partial class DetailsError
{
    /// <summary>Details of the error.</summary>
    [JsonPropertyName("details")]
    public string? Details { get; set; }
    [JsonPropertyName("failed_constraints")]
    public IEnumerable<DetailsErrorFailedConstraintsItem>? FailedConstraints { get; set; }
    /// <summary>The status code.</summary>
    [JsonPropertyName("status")]
    public decimal? Status { get; set; }
    /// <summary>Short title of the error.</summary>
    [JsonPropertyName("title")]
    public string? Title { get; set; }

    public override string ToString()
    {
        var builder = new StringBuilder();
        builder.Append("DetailsError");
        var hasValue = false;

        void Append(string label, object? value)
        {
            if (value is null)
            {
                return;
            }
            if (!hasValue)
            {
                builder.Append(" (");
                hasValue = true;
            }
            else
            {
                builder.Append(", ");
            }
            builder.Append(label).Append(": ").Append(value);
        }

        void Close()
        {
            if (hasValue)
            {
                builder.Append(")");
            }
        }
        if (!string.IsNullOrWhiteSpace(Details))
        {
            Append("details", Details);
        }
        if (FailedConstraints is not null)
        {
            Append("failed_constraints", FailedConstraints);
        }
        if (Status is not null)
        {
            Append("status", Status);
        }
        if (!string.IsNullOrWhiteSpace(Title))
        {
            Append("title", Title);
        }

        Close();
        if (hasValue)
        {
            return builder.ToString();
        }
        return JsonSerializer.Serialize(this);
    }
}