// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
public sealed partial class Device
{
    /// <summary>Device model.</summary>
    [JsonPropertyName("model")]
    public string? Model { get; set; }
    /// <summary>Device name.</summary>
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    /// <summary>Device OS.</summary>
    [JsonPropertyName("system_name")]
    public string? SystemName { get; set; }
    /// <summary>Device OS version.</summary>
    [JsonPropertyName("system_version")]
    public string? SystemVersion { get; set; }
    /// <summary>Device UUID.</summary>
    [JsonPropertyName("uuid")]
    public string? Uuid { get; set; }
}