// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
/// <summary>Doing Business As information</summary>
public sealed partial class DoingBusinessAsLegacy
{
    [JsonPropertyName("address")]
    public DoingBusinessAsLegacyAddress? Address { get; set; }
    /// <summary>Doing business as name</summary>
    [JsonPropertyName("business_name")]
    public string? BusinessName { get; set; }
    /// <summary>Doing business as company registration number</summary>
    [JsonPropertyName("company_registration_number")]
    public string? CompanyRegistrationNumber { get; set; }
    /// <summary>Doing business as email</summary>
    [JsonPropertyName("email")]
    public string? Email { get; set; }
    /// <summary>Doing business as VAT ID</summary>
    [JsonPropertyName("vat_id")]
    public string? VatId { get; set; }
    /// <summary>Doing business as website</summary>
    [JsonPropertyName("website")]
    public string? Website { get; set; }
}