// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
/// <summary>Doing Business As information</summary>
public sealed partial class DoingBusinessAsPayloadLegacy
{
    /// <summary>Personal address</summary>
    [JsonPropertyName("address")]
    public AddressPayloadLegacy? Address { get; set; }
    /// <summary>Doing business as name</summary>
    [JsonPropertyName("business_name")]
    public string? BusinessName { get; set; }
    /// <summary>Doing business as email</summary>
    [JsonPropertyName("email")]
    public string? Email { get; set; }
    /// <summary>Doing business as Tax ID</summary>
    [JsonPropertyName("tax_id")]
    public string? TaxId { get; set; }
    /// <summary>Doing business as VAT ID</summary>
    [JsonPropertyName("vat_id")]
    public string? VatId { get; set; }
    /// <summary>Doing business as website</summary>
    [JsonPropertyName("website")]
    public string? Website { get; set; }
}