// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
public sealed partial class ElvCardAccount
{
    /// <summary>ELV IBAN.</summary>
    [JsonPropertyName("iban")]
    public string? Iban { get; set; }
    /// <summary>ELV card account number last 4 digits.</summary>
    [JsonPropertyName("last_4_digits")]
    public string? Last4Digits { get; set; }
    /// <summary>ELV card sequence number.</summary>
    [JsonPropertyName("sequence_no")]
    public int? SequenceNo { get; set; }
    /// <summary>ELV card sort code.</summary>
    [JsonPropertyName("sort_code")]
    public string? SortCode { get; set; }
}