// <auto-generated />
#nullable enable

namespace SumUp;

using System.Runtime.Serialization;
using System.Text.Json.Serialization;

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum EntryModeFilter
{
    [EnumMember(Value = "BOLETO")]
    Boleto,
    [EnumMember(Value = "SOFORT")]
    Sofort,
    [EnumMember(Value = "IDEAL")]
    Ideal,
    [EnumMember(Value = "BANCONTACT")]
    Bancontact,
    [EnumMember(Value = "EPS")]
    Eps,
    [EnumMember(Value = "MYBANK")]
    Mybank,
    [EnumMember(Value = "SATISPAY")]
    Satispay,
    [EnumMember(Value = "BLIK")]
    Blik,
    [EnumMember(Value = "P24")]
    P24,
    [EnumMember(Value = "GIROPAY")]
    Giropay,
    [EnumMember(Value = "PIX")]
    Pix,
    [EnumMember(Value = "QR_CODE_PIX")]
    QrCodePix,
    [EnumMember(Value = "APPLE_PAY")]
    ApplePay,
    [EnumMember(Value = "GOOGLE_PAY")]
    GooglePay,
    [EnumMember(Value = "PAYPAL")]
    Paypal,
    [EnumMember(Value = "NONE")]
    None,
    [EnumMember(Value = "CHIP")]
    Chip,
    [EnumMember(Value = "MANUAL_ENTRY")]
    ManualEntry,
    [EnumMember(Value = "CUSTOMER_ENTRY")]
    CustomerEntry,
    [EnumMember(Value = "MAGSTRIPE_FALLBACK")]
    MagstripeFallback,
    [EnumMember(Value = "MAGSTRIPE")]
    Magstripe,
    [EnumMember(Value = "DIRECT_DEBIT")]
    DirectDebit,
    [EnumMember(Value = "CONTACTLESS")]
    Contactless,
    [EnumMember(Value = "MOTO")]
    Moto,
    [EnumMember(Value = "CONTACTLESS_MAGSTRIPE")]
    ContactlessMagstripe,
    [EnumMember(Value = "N/A")]
    NA,
}