// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
using System.Text.Json;
using System.Text;
/// <summary>Error payload with the invalid parameter reference.</summary>
public sealed partial class ErrorExtended
{
    /// <summary>Platform code for the error.</summary>
    [JsonPropertyName("error_code")]
    public string? ErrorCode { get; set; }
    /// <summary>Short description of the error.</summary>
    [JsonPropertyName("message")]
    public string? Message { get; set; }
    /// <summary>Parameter name (with relative location) to which the error applies. Parameters from embedded resources are displayed using dot notation. For example, `card.name` refers to the `name` parameter embedded in the `card` object.</summary>
    [JsonPropertyName("param")]
    public string? Param { get; set; }

    public override string ToString()
    {
        var builder = new StringBuilder();
        builder.Append("ErrorExtended");
        var hasValue = false;

        void Append(string label, object? value)
        {
            if (value is null)
            {
                return;
            }
            if (!hasValue)
            {
                builder.Append(" (");
                hasValue = true;
            }
            else
            {
                builder.Append(", ");
            }
            builder.Append(label).Append(": ").Append(value);
        }

        void Close()
        {
            if (hasValue)
            {
                builder.Append(")");
            }
        }
        if (!string.IsNullOrWhiteSpace(ErrorCode))
        {
            Append("error_code", ErrorCode);
        }
        if (!string.IsNullOrWhiteSpace(Message))
        {
            Append("message", Message);
        }
        if (!string.IsNullOrWhiteSpace(Param))
        {
            Append("param", Param);
        }

        Close();
        if (hasValue)
        {
            return builder.ToString();
        }
        return JsonSerializer.Serialize(this);
    }
}