// <auto-generated />
#nullable enable

namespace SumUp;

using System.Runtime.Serialization;
using System.Text.Json.Serialization;

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum ErrorCategoryServer
{
    [EnumMember(Value = "server_error")]
    ServerError,
}