// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
public sealed partial class ErrorExtended
{
    /// <summary>Platform code for the error.</summary>
    [JsonPropertyName("error_code")]
    public string? ErrorCode { get; set; }
    /// <summary>Short description of the error.</summary>
    [JsonPropertyName("message")]
    public string? Message { get; set; }
    /// <summary>Parameter name (with relative location) to which the error applies. Parameters from embedded resources are displayed using dot notation. For example, `card.name` refers to the `name` parameter embedded in the `card` object.</summary>
    [JsonPropertyName("param")]
    public string? Param { get; set; }
}