// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
/// <summary>Error message for forbidden requests.</summary>
public sealed partial class ErrorForbidden
{
    /// <summary>Platform code for the error.</summary>
    [JsonPropertyName("error_code")]
    public string? ErrorCode { get; set; }
    /// <summary>Short description of the error.</summary>
    [JsonPropertyName("error_message")]
    public string? ErrorMessage { get; set; }
    /// <summary>HTTP status code for the error.</summary>
    [JsonPropertyName("status_code")]
    public string? StatusCode { get; set; }
}