// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
public sealed partial class EventValue
{
    /// <summary>Amount of the event.</summary>
    [JsonPropertyName("amount")]
    public float? Amount { get; set; }
    /// <summary>Amount deducted for the event.</summary>
    [JsonPropertyName("deducted_amount")]
    public float? DeductedAmount { get; set; }
    /// <summary>Amount of the fee deducted for the event.</summary>
    [JsonPropertyName("deducted_fee_amount")]
    public float? DeductedFeeAmount { get; set; }
    /// <summary>Amount of the fee related to the event.</summary>
    [JsonPropertyName("fee_amount")]
    public float? FeeAmount { get; set; }
    /// <summary>Unique ID of the transaction event.</summary>
    [JsonPropertyName("id")]
    public long? Id { get; set; }
    /// <summary>Consecutive number of the installment.</summary>
    [JsonPropertyName("installment_number")]
    public int? InstallmentNumber { get; set; }
    /// <summary>Status of the transaction event.</summary>
    [JsonPropertyName("status")]
    public EventStatus? Status { get; set; }
    /// <summary>Date and time of the transaction event.</summary>
    [JsonPropertyName("timestamp")]
    public DateTimeOffset? Timestamp { get; set; }
    /// <summary>Unique ID of the transaction.</summary>
    [JsonPropertyName("transaction_id")]
    public string? TransactionId { get; set; }
    /// <summary>Type of the transaction event.</summary>
    [JsonPropertyName("type")]
    public EventType? Type { get; set; }
}