// <auto-generated />
#nullable enable

namespace SumUp;

using System.Runtime.Serialization;
using System.Text.Json.Serialization;

[JsonConverter(typeof(EnumMemberJsonConverterFactory))]
public enum EventStatus
{
    [EnumMember(Value = "FAILED")]
    Failed,
    [EnumMember(Value = "PAID_OUT")]
    PaidOut,
    [EnumMember(Value = "PENDING")]
    Pending,
    [EnumMember(Value = "RECONCILED")]
    Reconciled,
    [EnumMember(Value = "REFUNDED")]
    Refunded,
    [EnumMember(Value = "SCHEDULED")]
    Scheduled,
    [EnumMember(Value = "SUCCESSFUL")]
    Successful,
}