// <auto-generated />
#nullable enable

namespace SumUp;

using System.Runtime.Serialization;
using System.Text.Json.Serialization;

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum EventType
{
    [EnumMember(Value = "PAYOUT")]
    Payout,
    [EnumMember(Value = "CHARGE_BACK")]
    ChargeBack,
    [EnumMember(Value = "REFUND")]
    Refund,
    [EnumMember(Value = "PAYOUT_DEDUCTION")]
    PayoutDeduction,
}