// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
/// <summary>A single payout-related record. A record can represent either: - an actual payout sent to the merchant (type = PAYOUT) - a deduction applied against merchant funds for a refund, chargeback, direct debit return, or balance adjustment</summary>
public sealed partial class FinancialPayout
{
    /// <summary>Amount of the payout or deduction in major units.</summary>
    [JsonPropertyName("amount")]
    public float Amount { get; set; }
    /// <summary>Three-letter ISO 4217 currency code of the payout.</summary>
    [JsonPropertyName("currency")]
    public string Currency { get; set; } = default!;
    /// <summary>Payout date associated with the record, in YYYY-MM-DD format.</summary>
    [JsonPropertyName("date")]
    public DateOnly Date { get; set; }
    /// <summary>Fee amount associated with the payout record, in major units.</summary>
    [JsonPropertyName("fee")]
    public float Fee { get; set; }
    /// <summary>Unique identifier of the payout-related record.</summary>
    [JsonPropertyName("id")]
    public int Id { get; set; }
    /// <summary>Processor or payout reference associated with the record.</summary>
    [JsonPropertyName("reference")]
    public string Reference { get; set; } = default!;
    /// <summary>Merchant-facing outcome of the payout record.</summary>
    [JsonPropertyName("status")]
    public FinancialPayoutStatus Status { get; set; }
    /// <summary>Transaction code of the original sale associated with the payout or deduction.</summary>
    [JsonPropertyName("transaction_code")]
    public string TransactionCode { get; set; } = default!;
    /// <summary>High-level payout record category.</summary>
    [JsonPropertyName("type")]
    public FinancialPayoutType Type { get; set; }
}