// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
public sealed partial class FinancialPayoutsItem
{
    [JsonPropertyName("amount")]
    public float? Amount { get; set; }
    [JsonPropertyName("currency")]
    public string? Currency { get; set; }
    [JsonPropertyName("date")]
    public DateOnly? Date { get; set; }
    [JsonPropertyName("fee")]
    public float? Fee { get; set; }
    [JsonPropertyName("id")]
    public int? Id { get; set; }
    [JsonPropertyName("reference")]
    public string? Reference { get; set; }
    [JsonPropertyName("status")]
    public FinancialPayoutsItemStatus? Status { get; set; }
    [JsonPropertyName("transaction_code")]
    public string? TransactionCode { get; set; }
    [JsonPropertyName("type")]
    public FinancialPayoutsItemType? Type { get; set; }
}