// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
public sealed partial class GetReaderCheckoutResponseData
{
    /// <summary>Type of the card. Required for some countries</summary>
    [JsonPropertyName("card_type")]
    public GetReaderCheckoutResponseDataCardType CardType { get; set; }
    /// <summary>Unique identifier for the checkout</summary>
    [JsonPropertyName("checkout_id")]
    public Guid CheckoutId { get; set; }
    /// <summary>Client transaction identifier associated with the checkout</summary>
    [JsonPropertyName("client_transaction_id")]
    public string ClientTransactionId { get; set; } = default!;
    /// <summary>Checkout creation timestamp</summary>
    [JsonPropertyName("created_at")]
    public DateTimeOffset CreatedAt { get; set; }
    /// <summary>Number of installments for the transaction. Required for some countries.</summary>
    [JsonPropertyName("installments")]
    public int? Installments { get; set; }
    /// <summary>Payment failure reason</summary>
    [JsonPropertyName("payment_failure_reason")]
    public string? PaymentFailureReason { get; set; }
    /// <summary>Payment status from payments v2 event</summary>
    [JsonPropertyName("payment_status")]
    public string? PaymentStatus { get; set; }
    /// <summary>Type of the payment. Required for some countries</summary>
    [JsonPropertyName("payment_type")]
    public GetReaderCheckoutResponseDataPaymentType PaymentType { get; set; }
    /// <summary>Reader firmware version</summary>
    [JsonPropertyName("reader_firmware_version")]
    public string ReaderFirmwareVersion { get; set; } = default!;
    /// <summary>Device serial number</summary>
    [JsonPropertyName("reader_serial_number")]
    public string ReaderSerialNumber { get; set; } = default!;
    /// <summary>Current status of the checkout</summary>
    [JsonPropertyName("status")]
    public GetReaderCheckoutResponseDataStatus Status { get; set; }
    /// <summary>Amount structure. The amount is represented as an integer value altogether with the currency and the minor unit. For example, EUR 1.00 is represented as value 100 with minor unit of 2.</summary>
    [JsonPropertyName("total_amount")]
    public GetReaderCheckoutResponseDataTotalAmount TotalAmount { get; set; } = default!;
    /// <summary>Checkout last update timestamp</summary>
    [JsonPropertyName("updated_at")]
    public DateTimeOffset UpdatedAt { get; set; }
    /// <summary>Checkout expiration timestamp. After this time, the checkout will be automatically cancelled.</summary>
    [JsonPropertyName("valid_until")]
    public DateTimeOffset? ValidUntil { get; set; }
}