// <auto-generated />
#nullable enable

namespace SumUp;

using System.Runtime.Serialization;
using System.Text.Json.Serialization;

[JsonConverter(typeof(EnumMemberJsonConverterFactory))]
public enum GetReaderCheckoutResponseDataCardType
{
    [EnumMember(Value = "credit")]
    Credit,
    [EnumMember(Value = "debit")]
    Debit,
}