// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
public sealed partial class GetReaderCheckoutResponse
{
    [JsonPropertyName("data")]
    public GetReaderCheckoutResponseData Data { get; set; } = default!;
}