// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
/// <summary>500 Internal Server Error</summary>
public sealed partial class InternalServerError
{
    [JsonPropertyName("errors")]
    public InternalServerErrorErrors Errors { get; set; } = default!;
}