// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
/// <summary>Id of the legal type of the merchant profile</summary>
public sealed partial class LegalTypeLegacy
{
    /// <summary>Legal type short description</summary>
    [JsonPropertyName("description")]
    public string? Description { get; set; }
    /// <summary>Legal type description</summary>
    [JsonPropertyName("full_description")]
    public string? FullDescription { get; set; }
    /// <summary>Unique id</summary>
    [JsonPropertyName("id")]
    public decimal? Id { get; set; }
    /// <summary>Sole trader legal type if true</summary>
    [JsonPropertyName("sole_trader")]
    public bool? SoleTrader { get; set; }
}