// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
using System.Collections.Generic;
public sealed partial class ListPersonsResponseBody
{
    [JsonPropertyName("items")]
    public IEnumerable<Person> Items { get; set; } = default!;
}