// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
/// <summary>Mandate is passed when a card is to be tokenized</summary>
public sealed partial class MandatePayload
{
    /// <summary>Indicates the mandate type</summary>
    [JsonPropertyName("type")]
    public string Type { get; set; } = default!;
    /// <summary>Operating system and web client used by the end-user</summary>
    [JsonPropertyName("user_agent")]
    public string UserAgent { get; set; } = default!;
    /// <summary>IP address of the end user. Supports IPv4 and IPv6</summary>
    [JsonPropertyName("user_ip")]
    public string? UserIp { get; set; }
}