// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
/// <summary>Created mandate</summary>
public sealed partial class MandateResponse
{
    /// <summary>Merchant code which has the mandate</summary>
    [JsonPropertyName("merchant_code")]
    public string? MerchantCode { get; set; }
    /// <summary>Mandate status</summary>
    [JsonPropertyName("status")]
    public string? Status { get; set; }
    /// <summary>Indicates the mandate type</summary>
    [JsonPropertyName("type")]
    public string? Type { get; set; }
}