// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
/// <summary>Mandate details used when a checkout should create a reusable card token for future recurring or merchant-initiated payments.</summary>
public sealed partial class MandatePayload
{
    /// <summary>Type of mandate to create for the saved payment instrument.</summary>
    [JsonPropertyName("type")]
    public MandatePayloadType Type { get; set; }
    /// <summary>Browser or client user agent observed when consent was collected.</summary>
    [JsonPropertyName("user_agent")]
    public string UserAgent { get; set; } = default!;
    /// <summary>IP address of the payer when the mandate was accepted.</summary>
    [JsonPropertyName("user_ip")]
    public string? UserIp { get; set; }
}