// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
/// <summary>Information about the user associated with the membership.</summary>
public sealed partial class MembershipUser
{
    /// <summary>Classic identifiers of the user.</summary>
    [JsonPropertyName("classic")]
    public MembershipUserClassic? Classic { get; set; }
    /// <summary>Time when the user has been disabled. Applies only to virtual users (`virtual_user: true`).</summary>
    [JsonPropertyName("disabled_at")]
    public DateTimeOffset? DisabledAt { get; set; }
    /// <summary>End-User's preferred e-mail address. Its value MUST conform to the RFC 5322 [RFC5322] addr-spec syntax. The RP MUST NOT rely upon this value being unique, for unique identification use ID instead.</summary>
    [JsonPropertyName("email")]
    public string Email { get; set; } = default!;
    /// <summary>Identifier for the End-User (also called Subject).</summary>
    [JsonPropertyName("id")]
    public string Id { get; set; } = default!;
    /// <summary>True if the user has enabled MFA on login.</summary>
    [JsonPropertyName("mfa_on_login_enabled")]
    public bool MfaOnLoginEnabled { get; set; }
    /// <summary>User's preferred name. Used for display purposes only.</summary>
    [JsonPropertyName("nickname")]
    public string? Nickname { get; set; }
    /// <summary>URL of the End-User's profile picture. This URL refers to an image file (for example, a PNG, JPEG, or GIF image file), rather than to a Web page containing an image.</summary>
    [JsonPropertyName("picture")]
    public string? Picture { get; set; }
    /// <summary>True if the user is a service account.</summary>
    [JsonPropertyName("service_account_user")]
    public bool ServiceAccountUser { get; set; }
    /// <summary>True if the user is a virtual user (operator).</summary>
    [JsonPropertyName("virtual_user")]
    public bool VirtualUser { get; set; }
}