// <auto-generated />
#nullable enable

namespace SumUp;

using System.Runtime.Serialization;
using System.Text.Json.Serialization;

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum MembershipStatus
{
    [EnumMember(Value = "accepted")]
    Accepted,
    [EnumMember(Value = "pending")]
    Pending,
    [EnumMember(Value = "expired")]
    Expired,
    [EnumMember(Value = "disabled")]
    Disabled,
    [EnumMember(Value = "unknown")]
    Unknown,
}