// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
/// <summary>Information about the resource the membership is in.</summary>
public sealed partial class MembershipResource
{
    /// <summary>Object attributes that are modifiable only by SumUp applications.</summary>
    [JsonPropertyName("attributes")]
    public Attributes? Attributes { get; set; }
    /// <summary>The timestamp of when the membership resource was created.</summary>
    [JsonPropertyName("created_at")]
    public DateTimeOffset CreatedAt { get; set; } = default!;
    /// <summary>ID of the resource the membership is in.</summary>
    [JsonPropertyName("id")]
    public string Id { get; set; } = default!;
    /// <summary>Logo fo the resource.</summary>
    [JsonPropertyName("logo")]
    public string? Logo { get; set; }
    /// <summary>Display name of the resource.</summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = default!;
    /// <summary>The type of the membership resource. Possible values are: * `merchant` - merchant account(s) * `organization` - organization(s)</summary>
    [JsonPropertyName("type")]
    public string Type { get; set; } = default!;
    /// <summary>The timestamp of when the membership resource was last updated.</summary>
    [JsonPropertyName("updated_at")]
    public DateTimeOffset UpdatedAt { get; set; } = default!;
}