// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
using System.Collections.Generic;
public sealed partial class MembersUpdateRequest
{
    /// <summary>Object attributes that are modifiable only by SumUp applications.</summary>
    [JsonPropertyName("attributes")]
    public Attributes? Attributes { get; set; }
    /// <summary>Set of user-defined key-value pairs attached to the object. Partial updates are not supported. When updating, always submit whole metadata. Maximum of 64 parameters are allowed in the object.</summary>
    [JsonPropertyName("metadata")]
    public Metadata? Metadata { get; set; }
    [JsonPropertyName("roles")]
    public IEnumerable<string>? Roles { get; set; }
    /// <summary>Allows you to update user data of managed users.</summary>
    [JsonPropertyName("user")]
    public MembersUpdateRequestUser? User { get; set; }
}