// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
using System.Collections.Generic;
/// <summary>A member is user within specific resource identified by resource id, resource type, and associated roles.</summary>
public sealed partial class Member
{
    /// <summary>Object attributes that are modifiable only by SumUp applications.</summary>
    [JsonPropertyName("attributes")]
    public Attributes? Attributes { get; set; }
    /// <summary>The timestamp of when the member was created.</summary>
    [JsonPropertyName("created_at")]
    public DateTimeOffset CreatedAt { get; set; } = default!;
    /// <summary>ID of the member.</summary>
    [JsonPropertyName("id")]
    public string Id { get; set; } = default!;
    /// <summary>Pending invitation for membership.</summary>
    [JsonPropertyName("invite")]
    public Invite? Invite { get; set; }
    /// <summary>Set of user-defined key-value pairs attached to the object. Partial updates are not supported. When updating, always submit whole metadata. Maximum of 64 parameters are allowed in the object.</summary>
    [JsonPropertyName("metadata")]
    public Metadata? Metadata { get; set; }
    /// <summary>User's permissions.</summary>
    [JsonPropertyName("permissions")]
    public IEnumerable<string> Permissions { get; set; } = default!;
    /// <summary>User's roles.</summary>
    [JsonPropertyName("roles")]
    public IEnumerable<string> Roles { get; set; } = default!;
    /// <summary>The status of the membership.</summary>
    [JsonPropertyName("status")]
    public MembershipStatus Status { get; set; }
    /// <summary>The timestamp of when the member was last updated.</summary>
    [JsonPropertyName("updated_at")]
    public DateTimeOffset UpdatedAt { get; set; } = default!;
    /// <summary>Information about the user associated with the membership.</summary>
    [JsonPropertyName("user")]
    public MembershipUser? User { get; set; }
}