// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
using System.Collections.Generic;
public sealed partial class MembersListResponse
{
    [JsonPropertyName("items")]
    public IEnumerable<Member> Items { get; set; } = default!;
    [JsonPropertyName("total_count")]
    public int? TotalCount { get; set; }
}