// <auto-generated />
#nullable enable

namespace SumUp;

using System.Runtime.Serialization;
using System.Text.Json.Serialization;

[JsonConverter(typeof(EnumMemberJsonConverterFactory))]
public enum MerchantSettingsPayloadPayoutType
{
    [EnumMember(Value = "SINGLE_PAYMENT")]
    SinglePayment,
}