// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
public sealed partial class MerchantSettingsPayload
{
    /// <summary>Expected maximum amount of a single purchase</summary>
    [JsonPropertyName("expected_max_transaction_amount")]
    public decimal? ExpectedMaxTransactionAmount { get; set; }
    /// <summary>Gross settlement</summary>
    [JsonPropertyName("gross_settlement")]
    public bool? GrossSettlement { get; set; }
    /// <summary>If true, the merchant will not receive automatic payouts.</summary>
    [JsonPropertyName("payout_on_demand")]
    public bool? PayoutOnDemand { get; set; }
    /// <summary>If true, the merchant will be able to manage payout_on_demand settings</summary>
    [JsonPropertyName("payout_on_demand_available")]
    public string? PayoutOnDemandAvailable { get; set; }
    /// <summary>Payout period.</summary>
    [JsonPropertyName("payout_period")]
    public string? PayoutPeriod { get; set; }
    /// <summary>Payout type.</summary>
    [JsonPropertyName("payout_type")]
    public string? PayoutType { get; set; }
    /// <summary>Printers enabled.</summary>
    [JsonPropertyName("printers_enabled")]
    public bool? PrintersEnabled { get; set; }
}