// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
/// <summary>Details of the merchant account.</summary>
public sealed partial class MerchantAccount
{
    /// <summary>Profile information.</summary>
    [JsonPropertyName("account")]
    public AccountLegacy? Account { get; set; }
    /// <summary>Mobile app settings</summary>
    [JsonPropertyName("app_settings")]
    public AppSettings? AppSettings { get; set; }
    /// <summary>Account's merchant profile</summary>
    [JsonPropertyName("merchant_profile")]
    public MerchantProfileLegacy? MerchantProfile { get; set; }
    /// <summary>User permissions</summary>
    [JsonPropertyName("permissions")]
    public PermissionsLegacy? Permissions { get; set; }
    /// <summary>Account's personal profile.</summary>
    [JsonPropertyName("personal_profile")]
    public PersonalProfileLegacy? PersonalProfile { get; set; }
}