// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
using System.Collections.Generic;
/// <summary>Account's merchant profile</summary>
public sealed partial class MerchantProfilePayload
{
    /// <summary>Personal address</summary>
    [JsonPropertyName("address")]
    public AddressPayloadLegacy Address { get; set; } = default!;
    /// <summary>Business owners information.</summary>
    [JsonPropertyName("business_owners")]
    public IEnumerable<BusinessOwnersItem>? BusinessOwners { get; set; }
    /// <summary>Company name</summary>
    [JsonPropertyName("company_name")]
    public string CompanyName { get; set; } = default!;
    /// <summary>Company registration number</summary>
    [JsonPropertyName("company_registration_number")]
    public string CompanyRegistrationNumber { get; set; } = default!;
    [JsonPropertyName("doing_business_as")]
    public MerchantProfilePayloadDoingBusinessAs? DoingBusinessAs { get; set; }
    /// <summary>Defines if the profile nature is for testing</summary>
    [JsonPropertyName("is_test_account")]
    public bool? IsTestAccount { get; set; }
    /// <summary>Id of the legal type of the merchant</summary>
    [JsonPropertyName("legal_type_id")]
    public decimal LegalTypeId { get; set; }
    /// <summary>Merchant category code</summary>
    [JsonPropertyName("merchant_category_code")]
    public string MerchantCategoryCode { get; set; } = default!;
    /// <summary>Mobile number</summary>
    [JsonPropertyName("mobile_phone")]
    public string? MobilePhone { get; set; }
    /// <summary>Nature and purpose of the business. Required for the following merchant category codes: 5999, 7392, 8999, 5694, 5969, 7299, 7399</summary>
    [JsonPropertyName("nature_and_purpose")]
    public string? NatureAndPurpose { get; set; }
    /// <summary>Payment certificate access code</summary>
    [JsonPropertyName("permanent_certificate_access_code")]
    public string? PermanentCertificateAccessCode { get; set; }
    /// <summary>Vat ID</summary>
    [JsonPropertyName("vat_id")]
    public string? VatId { get; set; }
    /// <summary>Company website</summary>
    [JsonPropertyName("website")]
    public string? Website { get; set; }
}