// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
/// <summary>404 Not Found</summary>
public sealed partial class NotFound
{
    [JsonPropertyName("errors")]
    public NotFoundErrors Errors { get; set; } = default!;
}