// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
/// <summary>Operator account for a merchant.</summary>
public sealed partial class OperatorValue
{
    [JsonPropertyName("account_type")]
    public string AccountType { get; set; } = default!;
    /// <summary>The timestamp of when the operator was created.</summary>
    [JsonPropertyName("created_at")]
    public DateTimeOffset CreatedAt { get; set; } = default!;
    [JsonPropertyName("disabled")]
    public bool Disabled { get; set; }
    [JsonPropertyName("id")]
    public int Id { get; set; }
    [JsonPropertyName("nickname")]
    public string? Nickname { get; set; }
    /// <summary>Permissions assigned to an operator or user.</summary>
    [JsonPropertyName("permissions")]
    public Permissions Permissions { get; set; } = default!;
    /// <summary>The timestamp of when the operator was last updated.</summary>
    [JsonPropertyName("updated_at")]
    public DateTimeOffset UpdatedAt { get; set; } = default!;
    [JsonPropertyName("username")]
    public string Username { get; set; } = default!;
}