// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
public sealed partial class Ownership
{
    /// <summary>The percent of ownership shares held by the Person expressed in percent mille (1/100000). Only Persons with the relationship owner can have ownership.</summary>
    [JsonPropertyName("share")]
    public int Share { get; set; }
}