// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
/// <summary>Details of the payment card that is saved as a payment instrument.</summary>
public sealed partial class PaymentInstrumentCard
{
    /// <summary>__Required when payment type is `card`.__ Details of the payment card.</summary>
    [JsonPropertyName("card")]
    public Card Card { get; set; } = default!;
    /// <summary>Type of the payment instrument.</summary>
    [JsonPropertyName("type")]
    public string Type { get; set; } = default!;
}