// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
/// <summary>Details of a saved payment instrument.</summary>
public sealed partial class PaymentInstrumentResponse
{
    /// <summary>Indicates whether the payment instrument is active and can be used for payments. To deactivate it, send a DELETE request to the resource endpoint.</summary>
    [JsonPropertyName("active")]
    [JsonInclude]
    public bool? Active { get; private set; }
    /// <summary>Details of the payment card.</summary>
    [JsonPropertyName("card")]
    public PaymentInstrumentResponseCard? Card { get; set; }
    /// <summary>The timestamp of when the payment instrument was created.</summary>
    [JsonPropertyName("created_at")]
    public DateTimeOffset? CreatedAt { get; set; }
    /// <summary>Details of the mandate linked to the saved payment instrument.</summary>
    [JsonPropertyName("mandate")]
    public MandateResponse? Mandate { get; set; }
    /// <summary>Token identifying the customer's saved payment card. Pass it as token, together with the associated customer_id and payment_type = card, when processing a checkout with this instrument.</summary>
    [JsonPropertyName("token")]
    [JsonInclude]
    public string? Token { get; private set; }
    /// <summary>Type of the payment instrument.</summary>
    [JsonPropertyName("type")]
    public PaymentInstrumentResponseType? Type { get; set; }
}