// <auto-generated />
#nullable enable

namespace SumUp;

using System.Runtime.Serialization;
using System.Text.Json.Serialization;

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum PaymentType
{
    [EnumMember(Value = "CASH")]
    Cash,
    [EnumMember(Value = "POS")]
    Pos,
    [EnumMember(Value = "ECOM")]
    Ecom,
    [EnumMember(Value = "RECURRING")]
    Recurring,
    [EnumMember(Value = "BITCOIN")]
    Bitcoin,
    [EnumMember(Value = "BALANCE")]
    Balance,
    [EnumMember(Value = "MOTO")]
    Moto,
    [EnumMember(Value = "BOLETO")]
    Boleto,
    [EnumMember(Value = "DIRECT_DEBIT")]
    DirectDebit,
    [EnumMember(Value = "APM")]
    Apm,
    [EnumMember(Value = "UNKNOWN")]
    Unknown,
}