// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
/// <summary>Permissions assigned to an operator or user.</summary>
public sealed partial class Permissions
{
    [JsonPropertyName("admin")]
    public bool Admin { get; set; }
    [JsonPropertyName("create_moto_payments")]
    public bool CreateMotoPayments { get; set; }
    [JsonPropertyName("create_referral")]
    public bool CreateReferral { get; set; }
    [JsonPropertyName("full_transaction_history_view")]
    public bool FullTransactionHistoryView { get; set; }
    [JsonPropertyName("refund_transactions")]
    public bool RefundTransactions { get; set; }
}