// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
/// <summary>User permissions</summary>
public sealed partial class PermissionsLegacy
{
    /// <summary>Create MOTO payments</summary>
    [JsonPropertyName("create_moto_payments")]
    public bool? CreateMotoPayments { get; set; }
    /// <summary>Create referral</summary>
    [JsonPropertyName("create_referral")]
    public bool? CreateReferral { get; set; }
    /// <summary>Can view full merchant transaction history</summary>
    [JsonPropertyName("full_transaction_history_view")]
    public bool? FullTransactionHistoryView { get; set; }
    /// <summary>Refund transactions</summary>
    [JsonPropertyName("refund_transactions")]
    public bool? RefundTransactions { get; set; }
}