// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
/// <summary>Account's personal profile.</summary>
public sealed partial class PersonalProfilePayloadLegacy
{
    /// <summary>Personal address</summary>
    [JsonPropertyName("address")]
    public AddressPayloadLegacy Address { get; set; } = default!;
    /// <summary>Date of birth</summary>
    [JsonPropertyName("date_of_birth")]
    public DateTime DateOfBirth { get; set; } = default!;
    /// <summary>First name of the user</summary>
    [JsonPropertyName("first_name")]
    public string FirstName { get; set; } = default!;
    /// <summary>Last name of the user</summary>
    [JsonPropertyName("last_name")]
    public string LastName { get; set; } = default!;
    /// <summary>Mobile phone number</summary>
    [JsonPropertyName("mobile_phone")]
    public string? MobilePhone { get; set; }
    /// <summary>National identification id. Country specific. Ex CPF &#40;Brazil&#41;, DNI (Spain), PESEL (Poland)</summary>
    [JsonPropertyName("national_id")]
    public string? NationalId { get; set; }
}