// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
/// <summary>Personal details for the customer.</summary>
public sealed partial class PersonalDetails
{
    /// <summary>Profile's personal address information.</summary>
    [JsonPropertyName("address")]
    public AddressLegacy? Address { get; set; }
    /// <summary>Date of birth of the customer.</summary>
    [JsonPropertyName("birth_date")]
    public DateTime? BirthDate { get; set; }
    /// <summary>Email address of the customer.</summary>
    [JsonPropertyName("email")]
    public string? Email { get; set; }
    /// <summary>First name of the customer.</summary>
    [JsonPropertyName("first_name")]
    public string? FirstName { get; set; }
    /// <summary>Last name of the customer.</summary>
    [JsonPropertyName("last_name")]
    public string? LastName { get; set; }
    /// <summary>Phone number of the customer.</summary>
    [JsonPropertyName("phone")]
    public string? Phone { get; set; }
    /// <summary>An identification number user for tax purposes (e.g. CPF)</summary>
    [JsonPropertyName("tax_id")]
    public string? TaxId { get; set; }
}