// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
/// <summary>Purchase product.</summary>
public sealed partial class Product
{
    /// <summary>Product name.</summary>
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    /// <summary>Product price.</summary>
    [JsonPropertyName("price")]
    public decimal? Price { get; set; }
    /// <summary>Product description.</summary>
    [JsonPropertyName("price_label")]
    public string? PriceLabel { get; set; }
    /// <summary>Product price incl. VAT.</summary>
    [JsonPropertyName("price_with_vat")]
    public decimal? PriceWithVat { get; set; }
    /// <summary>Product quantity.</summary>
    [JsonPropertyName("quantity")]
    public int? Quantity { get; set; }
    /// <summary>VAT amount for a single product.</summary>
    [JsonPropertyName("single_vat_amount")]
    public decimal? SingleVatAmount { get; set; }
    /// <summary>Quantity x product price.</summary>
    [JsonPropertyName("total_price")]
    public decimal? TotalPrice { get; set; }
    /// <summary>Total price incl. VAT.</summary>
    [JsonPropertyName("total_with_vat")]
    public decimal? TotalWithVat { get; set; }
    /// <summary>VAT amount.</summary>
    [JsonPropertyName("vat_amount")]
    public decimal? VatAmount { get; set; }
    /// <summary>VAT percentage.</summary>
    [JsonPropertyName("vat_rate")]
    public decimal? VatRate { get; set; }
}