// <auto-generated />
#nullable enable

namespace SumUp;

using System.Runtime.Serialization;
using System.Text.Json.Serialization;

[JsonConverter(typeof(EnumMemberJsonConverterFactory))]
public enum ReaderCheckoutStatusChangePayloadStatus
{
    [EnumMember(Value = "successful")]
    Successful,
    [EnumMember(Value = "failed")]
    Failed,
}