// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
/// <summary>The callback payload containing the status change of the Reader Checkout.</summary>
public sealed partial class ReaderCheckoutStatusChange
{
    /// <summary>Type of event.</summary>
    [JsonPropertyName("event_type")]
    public string EventType { get; set; } = default!;
    /// <summary>Unique identifier for the event.</summary>
    [JsonPropertyName("id")]
    public Guid Id { get; set; } = default!;
    /// <summary>The event payload.</summary>
    [JsonPropertyName("payload")]
    public ReaderCheckoutStatusChangePayload Payload { get; set; } = default!;
    /// <summary>Timestamp of the event.</summary>
    [JsonPropertyName("timestamp")]
    public DateTimeOffset Timestamp { get; set; } = default!;
}