// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
public sealed partial class ReadersCreateRequest
{
    /// <summary>Set of user-defined key-value pairs attached to the object. Partial updates are not supported. When updating, always submit whole metadata. Maximum of 64 parameters are allowed in the object.</summary>
    [JsonPropertyName("metadata")]
    public Metadata? Metadata { get; set; }
    /// <summary>Custom human-readable, user-defined name for easier identification of the reader.</summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = default!;
    /// <summary>The pairing code is a 8 or 9 character alphanumeric string that is displayed on a SumUp Device after initiating the pairing. It is used to link the physical device to the created pairing.</summary>
    [JsonPropertyName("pairing_code")]
    public string PairingCode { get; set; } = default!;
}