// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
/// <summary>Information about the underlying physical device.</summary>
public sealed partial class ReaderDevice
{
    /// <summary>A unique identifier of the physical device (e.g. serial number).</summary>
    [JsonPropertyName("identifier")]
    public string Identifier { get; set; } = default!;
    /// <summary>Identifier of the model of the device.</summary>
    [JsonPropertyName("model")]
    public string Model { get; set; } = default!;
}