// <auto-generated />
#nullable enable

namespace SumUp;

using System.Runtime.Serialization;
using System.Text.Json.Serialization;

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum ReaderStatus
{
    [EnumMember(Value = "unknown")]
    Unknown,
    [EnumMember(Value = "processing")]
    Processing,
    [EnumMember(Value = "paired")]
    Paired,
    [EnumMember(Value = "expired")]
    Expired,
}