// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
public sealed partial class ReaderPaymentResponseData
{
    /// <summary>Caller-supplied correlation identifier that was provided in the request.</summary>
    [JsonPropertyName("client_transaction_id")]
    public string? ClientTransactionId { get; set; }
    /// <summary>Transaction code returned by the acquirer/processing entity after processing the transaction.</summary>
    [JsonPropertyName("transaction_code")]
    public string? TransactionCode { get; set; }
}