// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
public sealed partial class ReceiptMerchantDataMerchantProfileAddress
{
    [JsonPropertyName("address_line1")]
    public string? AddressLine1 { get; set; }
    [JsonPropertyName("city")]
    public string? City { get; set; }
    [JsonPropertyName("country")]
    public string? Country { get; set; }
    [JsonPropertyName("country_en_name")]
    public string? CountryEnName { get; set; }
    [JsonPropertyName("country_native_name")]
    public string? CountryNativeName { get; set; }
    [JsonPropertyName("landline")]
    public string? Landline { get; set; }
    [JsonPropertyName("post_code")]
    public string? PostCode { get; set; }
}