// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
/// <summary>Card reader details displayed on the receipt.</summary>
public sealed partial class ReceiptReader
{
    /// <summary>Unique identifier of the physical card reader.</summary>
    [JsonPropertyName("code")]
    public string? Code { get; set; }
    /// <summary>Model of the physical card reader.</summary>
    [JsonPropertyName("type")]
    public string? Type { get; set; }
}