// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
/// <summary>Receipt details for a transaction.</summary>
public sealed partial class Receipt
{
    /// <summary>Acquirer-specific metadata related to the card authorization.</summary>
    [JsonPropertyName("acquirer_data")]
    public ReceiptAcquirerData? AcquirerData { get; set; }
    /// <summary>EMV-specific metadata returned for card-present payments.</summary>
    [JsonPropertyName("emv_data")]
    public JsonObject? EmvData { get; set; }
    /// <summary>Merchant details displayed on a transaction receipt.</summary>
    [JsonPropertyName("merchant_data")]
    public ReceiptMerchantData? MerchantData { get; set; }
    /// <summary>Transaction details displayed on a receipt.</summary>
    [JsonPropertyName("transaction_data")]
    public ReceiptTransaction? TransactionData { get; set; }
}