// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
using System.Collections.Generic;
/// <summary>Transaction information.</summary>
public sealed partial class ReceiptTransaction
{
    /// <summary>Transaction amount.</summary>
    [JsonPropertyName("amount")]
    public string? Amount { get; set; }
    [JsonPropertyName("card")]
    public ReceiptCard? Card { get; set; }
    /// <summary>Transaction currency.</summary>
    [JsonPropertyName("currency")]
    public string? Currency { get; set; }
    /// <summary>Transaction entry mode.</summary>
    [JsonPropertyName("entry_mode")]
    public string? EntryMode { get; set; }
    /// <summary>Events</summary>
    [JsonPropertyName("events")]
    public IEnumerable<ReceiptEvent>? Events { get; set; }
    /// <summary>Number of installments.</summary>
    [JsonPropertyName("installments_count")]
    public int? InstallmentsCount { get; set; }
    /// <summary>Transaction type.</summary>
    [JsonPropertyName("payment_type")]
    public string? PaymentType { get; set; }
    /// <summary>Products</summary>
    [JsonPropertyName("products")]
    public IEnumerable<ReceiptTransactionProductsItem>? Products { get; set; }
    /// <summary>Receipt number</summary>
    [JsonPropertyName("receipt_no")]
    public string? ReceiptNo { get; set; }
    /// <summary>Transaction processing status.</summary>
    [JsonPropertyName("status")]
    public string? Status { get; set; }
    /// <summary>Time created at.</summary>
    [JsonPropertyName("timestamp")]
    public DateTimeOffset? Timestamp { get; set; }
    /// <summary>Tip amount (included in transaction amount).</summary>
    [JsonPropertyName("tip_amount")]
    public string? TipAmount { get; set; }
    /// <summary>Transaction code.</summary>
    [JsonPropertyName("transaction_code")]
    public string? TransactionCode { get; set; }
    /// <summary>Transaction VAT amount.</summary>
    [JsonPropertyName("vat_amount")]
    public string? VatAmount { get; set; }
    /// <summary>Vat rates.</summary>
    [JsonPropertyName("vat_rates")]
    public IEnumerable<ReceiptTransactionVatRatesItem>? VatRates { get; set; }
    /// <summary>Cardholder verification method.</summary>
    [JsonPropertyName("verification_method")]
    public string? VerificationMethod { get; set; }
}