// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
public sealed partial class ReceiptMerchantDataMerchantProfile
{
    [JsonPropertyName("address")]
    public ReceiptMerchantDataMerchantProfileAddress? Address { get; set; }
    [JsonPropertyName("business_name")]
    public string? BusinessName { get; set; }
    [JsonPropertyName("email")]
    public string? Email { get; set; }
    [JsonPropertyName("merchant_code")]
    public string? MerchantCode { get; set; }
}