// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
using System.Text.Json;
public sealed partial class Receipt
{
    [JsonPropertyName("acquirer_data")]
    public ReceiptAcquirerData? AcquirerData { get; set; }
    [JsonPropertyName("emv_data")]
    public JsonDocument? EmvData { get; set; }
    /// <summary>Receipt merchant data</summary>
    [JsonPropertyName("merchant_data")]
    public ReceiptMerchantData? MerchantData { get; set; }
    /// <summary>Transaction information.</summary>
    [JsonPropertyName("transaction_data")]
    public ReceiptTransaction? TransactionData { get; set; }
}