// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
public sealed partial class ReceiptCard
{
    /// <summary>Card last 4 digits.</summary>
    [JsonPropertyName("last_4_digits")]
    public string? Last4Digits { get; set; }
    /// <summary>Card Scheme.</summary>
    [JsonPropertyName("type")]
    public string? Type { get; set; }
}