// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
public sealed partial class ReceiptAcquirerData
{
    [JsonPropertyName("authorization_code")]
    public string? AuthorizationCode { get; set; }
    [JsonPropertyName("local_time")]
    public string? LocalTime { get; set; }
    [JsonPropertyName("return_code")]
    public string? ReturnCode { get; set; }
    [JsonPropertyName("tid")]
    public string? Tid { get; set; }
}