// <auto-generated />
#nullable enable

namespace SumUp;

using System.Runtime.Serialization;
using System.Text.Json.Serialization;

[JsonConverter(typeof(EnumMemberJsonConverterFactory))]
public enum ReceiptTransactionProcessAs
{
    [EnumMember(Value = "CREDIT")]
    Credit,
    [EnumMember(Value = "DEBIT")]
    Debit,
}