// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
public sealed partial class ReceiptTransactionProductsItem
{
    /// <summary>Product description.</summary>
    [JsonPropertyName("description")]
    public string? Description { get; set; }
    /// <summary>Product name.</summary>
    [JsonPropertyName("name")]
    public string? Name { get; set; }
    /// <summary>Product price.</summary>
    [JsonPropertyName("price")]
    public float? Price { get; set; }
    /// <summary>Product quantity.</summary>
    [JsonPropertyName("quantity")]
    public int? Quantity { get; set; }
    /// <summary>Quantity x product price.</summary>
    [JsonPropertyName("total_price")]
    public float? TotalPrice { get; set; }
}