// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
using System.Collections.Generic;
public sealed partial class RolesCreateRequest
{
    /// <summary>User-defined description of the role.</summary>
    [JsonPropertyName("description")]
    public string? Description { get; set; }
    /// <summary>Set of user-defined key-value pairs attached to the object. Partial updates are not supported. When updating, always submit whole metadata. Maximum of 64 parameters are allowed in the object.</summary>
    [JsonPropertyName("metadata")]
    public Metadata? Metadata { get; set; }
    /// <summary>User-defined name of the role.</summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = default!;
    /// <summary>User's permissions.</summary>
    [JsonPropertyName("permissions")]
    public IEnumerable<string> Permissions { get; set; } = default!;
}