// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
using System.Collections.Generic;
public sealed partial class RolesListResponse
{
    [JsonPropertyName("items")]
    public IEnumerable<Role> Items { get; set; } = default!;
}