// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
using System.Collections.Generic;
/// <summary>A custom role that can be used to assign set of permissions to members.</summary>
public sealed partial class Role
{
    /// <summary>The timestamp of when the role was created.</summary>
    [JsonPropertyName("created_at")]
    public DateTimeOffset CreatedAt { get; set; } = default!;
    /// <summary>User-defined description of the role.</summary>
    [JsonPropertyName("description")]
    public string? Description { get; set; }
    /// <summary>Unique identifier of the role.</summary>
    [JsonPropertyName("id")]
    public string Id { get; set; } = default!;
    /// <summary>True if the role is provided by SumUp.</summary>
    [JsonPropertyName("is_predefined")]
    public bool IsPredefined { get; set; }
    /// <summary>Set of user-defined key-value pairs attached to the object. Partial updates are not supported. When updating, always submit whole metadata. Maximum of 64 parameters are allowed in the object.</summary>
    [JsonPropertyName("metadata")]
    public Metadata? Metadata { get; set; }
    /// <summary>User-defined name of the role.</summary>
    [JsonPropertyName("name")]
    public string Name { get; set; } = default!;
    /// <summary>List of permission granted by this role.</summary>
    [JsonPropertyName("permissions")]
    public IEnumerable<string> Permissions { get; set; } = default!;
    /// <summary>The timestamp of when the role was last updated.</summary>
    [JsonPropertyName("updated_at")]
    public DateTimeOffset UpdatedAt { get; set; } = default!;
}