// <auto-generated />
#nullable enable

namespace SumUp;

using System.Runtime.Serialization;
using System.Text.Json.Serialization;

[JsonConverter(typeof(EnumMemberJsonConverterFactory))]
public enum StatusResponseDataConnectionType
{
    [EnumMember(Value = "btle")]
    Btle,
    [EnumMember(Value = "edge")]
    Edge,
    [EnumMember(Value = "gprs")]
    Gprs,
    [EnumMember(Value = "lte")]
    Lte,
    [EnumMember(Value = "umts")]
    Umts,
    [EnumMember(Value = "usb")]
    Usb,
    [EnumMember(Value = "Wi-Fi")]
    WiFi,
}