// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
/// <summary>Status of a device</summary>
public sealed partial class StatusResponse
{
    [JsonPropertyName("data")]
    public StatusResponseData Data { get; set; } = default!;
}