// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
public sealed partial class SubaccountsCreateSubAccountRequest
{
    [JsonPropertyName("nickname")]
    public string? Nickname { get; set; }
    [JsonPropertyName("password")]
    public string Password { get; set; } = default!;
    [JsonPropertyName("permissions")]
    public SubaccountsCreateSubAccountRequestPermissions? Permissions { get; set; }
    [JsonPropertyName("username")]
    public string Username { get; set; } = default!;
}