// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
public sealed partial class SubaccountsUpdateSubAccountRequestPermissions
{
    [JsonPropertyName("create_moto_payments")]
    public bool? CreateMotoPayments { get; set; }
    [JsonPropertyName("create_referral")]
    public bool? CreateReferral { get; set; }
    [JsonPropertyName("full_transaction_history_view")]
    public bool? FullTransactionHistoryView { get; set; }
    [JsonPropertyName("refund_transactions")]
    public bool? RefundTransactions { get; set; }
}