// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
public sealed partial class Timestamps
{
    /// <summary>The date and time when the resource was created. This is a string as defined in [RFC 3339, section 5.6](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6).</summary>
    [JsonPropertyName("created_at")]
    public DateTimeOffset CreatedAt { get; } = default!;
    /// <summary>The date and time when the resource was last updated. This is a string as defined in [RFC 3339, section 5.6](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6).</summary>
    [JsonPropertyName("updated_at")]
    public DateTimeOffset UpdatedAt { get; } = default!;
}