// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
/// <summary>TimeOffset Details</summary>
public sealed partial class TimeoffsetDetails
{
    /// <summary>Daylight Saving Time</summary>
    [JsonPropertyName("dst")]
    public bool? Dst { get; set; }
    /// <summary>UTC offset</summary>
    [JsonPropertyName("offset")]
    public decimal? Offset { get; set; }
    /// <summary>Postal code</summary>
    [JsonPropertyName("post_code")]
    public string? PostCode { get; set; }
}