// <auto-generated />
#nullable enable

namespace SumUp;

using System.Runtime.Serialization;
using System.Text.Json.Serialization;

[JsonConverter(typeof(EnumMemberJsonConverterFactory))]
public enum TransactionFullPayoutType
{
    [EnumMember(Value = "BANK_ACCOUNT")]
    BankAccount,
    [EnumMember(Value = "PREPAID_CARD")]
    PrepaidCard,
}