// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
public sealed partial class TransactionCheckoutInfo
{
    /// <summary>Authorization code for the transaction sent by the payment card issuer or bank. Applicable only to card payments.</summary>
    [JsonPropertyName("auth_code")]
    public string? AuthCode { get; set; }
    /// <summary>Entry mode of the payment details.</summary>
    [JsonPropertyName("entry_mode")]
    public EntryMode? EntryMode { get; set; }
    /// <summary>Internal unique ID of the transaction on the SumUp platform.</summary>
    [JsonPropertyName("internal_id")]
    public long? InternalId { get; set; }
    /// <summary>Unique code of the registered merchant to whom the payment is made.</summary>
    [JsonPropertyName("merchant_code")]
    public string? MerchantCode { get; set; }
    /// <summary>Amount of the tip (out of the total transaction amount).</summary>
    [JsonPropertyName("tip_amount")]
    public float? TipAmount { get; set; }
    /// <summary>Amount of the applicable VAT (out of the total transaction amount).</summary>
    [JsonPropertyName("vat_amount")]
    public float? VatAmount { get; set; }
}