// <auto-generated />
#nullable enable

namespace SumUp;

using System.Runtime.Serialization;
using System.Text.Json.Serialization;

[JsonConverter(typeof(EnumMemberJsonConverterFactory))]
public enum TransactionFullVerificationMethod
{
    [EnumMember(Value = "none")]
    None,
    [EnumMember(Value = "signature")]
    Signature,
    [EnumMember(Value = "offline PIN")]
    OfflinePin,
    [EnumMember(Value = "online PIN")]
    OnlinePin,
    [EnumMember(Value = "offline PIN + signature")]
    OfflinePinSignature,
    [EnumMember(Value = "na")]
    Na,
}