// <auto-generated />
#nullable enable

namespace SumUp;

using System.Runtime.Serialization;
using System.Text.Json.Serialization;

[JsonConverter(typeof(EnumMemberJsonConverterFactory))]
public enum TransactionHistoryType
{
    [EnumMember(Value = "PAYMENT")]
    Payment,
    [EnumMember(Value = "REFUND")]
    Refund,
    [EnumMember(Value = "CHARGE_BACK")]
    ChargeBack,
}