// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
/// <summary>Details of the payment location as received from the payment terminal.</summary>
public sealed partial class TransactionFullLocation
{
    /// <summary>Indication of the precision of the geographical position received from the payment terminal.</summary>
    [JsonPropertyName("horizontal_accuracy")]
    public float? HorizontalAccuracy { get; set; }
    /// <summary>Latitude value from the coordinates of the payment location (as received from the payment terminal reader).</summary>
    [JsonPropertyName("lat")]
    public float? Lat { get; set; }
    /// <summary>Longitude value from the coordinates of the payment location (as received from the payment terminal reader).</summary>
    [JsonPropertyName("lon")]
    public float? Lon { get; set; }
}