// <auto-generated />
#nullable enable

namespace SumUp;

using System.Runtime.Serialization;
using System.Text.Json.Serialization;

[JsonConverter(typeof(EnumMemberJsonConverterFactory))]
public enum TransactionFullPayoutPlan
{
    [EnumMember(Value = "SINGLE_PAYMENT")]
    SinglePayment,
    [EnumMember(Value = "TRUE_INSTALLMENT")]
    TrueInstallment,
    [EnumMember(Value = "ACCELERATED_INSTALLMENT")]
    AcceleratedInstallment,
}