// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
public sealed partial class TransactionsHistoryLink
{
    /// <summary>Location.</summary>
    [JsonPropertyName("href")]
    public string Href { get; set; } = default!;
    /// <summary>Relation.</summary>
    [JsonPropertyName("rel")]
    public string Rel { get; set; } = default!;
}