// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
/// <summary>Optional amount for partial refunds of transactions.</summary>
public sealed partial class TransactionsRefundRequest
{
    /// <summary>Amount to be refunded. Eligible amount can't exceed the amount of the transaction and varies based on country and currency. If you do not specify a value, the system performs a full refund of the transaction.</summary>
    [JsonPropertyName("amount")]
    public float? Amount { get; set; }
}