// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
using System.Collections.Generic;
public sealed partial class TransactionsListDeprecatedResponse
{
    [JsonPropertyName("items")]
    public IEnumerable<TransactionHistory>? Items { get; set; }
    [JsonPropertyName("links")]
    public IEnumerable<Link>? Links { get; set; }
}