// <auto-generated />
#nullable enable

namespace SumUp;

using System.Runtime.Serialization;
using System.Text.Json.Serialization;

[JsonConverter(typeof(EnumMemberJsonConverterFactory))]
public enum TransactionFullSimpleStatus
{
    [EnumMember(Value = "SUCCESSFUL")]
    Successful,
    [EnumMember(Value = "PAID_OUT")]
    PaidOut,
    [EnumMember(Value = "CANCEL_FAILED")]
    CancelFailed,
    [EnumMember(Value = "CANCELLED")]
    Cancelled,
    [EnumMember(Value = "CHARGEBACK")]
    Chargeback,
    [EnumMember(Value = "FAILED")]
    Failed,
    [EnumMember(Value = "REFUND_FAILED")]
    RefundFailed,
    [EnumMember(Value = "REFUNDED")]
    Refunded,
    [EnumMember(Value = "NON_COLLECTION")]
    NonCollection,
    [EnumMember(Value = "PENDING")]
    Pending,
}