// <auto-generated />
#nullable enable

namespace SumUp;

using System.Text.Json.Serialization;
public sealed partial class UnauthorizedErrors
{
    /// <summary>Fuller message giving context to error</summary>
    [JsonPropertyName("detail")]
    public string Detail { get; set; } = default!;
    /// <summary>Key indicating type of error. Present only for typed 401 responses (e.g. invalid token, invalid password). Absent for generic unauthorized responses.</summary>
    [JsonPropertyName("type")]
    public string? Type { get; set; }
}