// <auto-generated />
#nullable enable

namespace SumUp;

using System.Runtime.Serialization;
using System.Text.Json.Serialization;

[JsonConverter(typeof(EnumMemberJsonConverterFactory))]
public enum UnauthorizedErrorsType
{
    [EnumMember(Value = "INVALID_ACCESS_TOKEN")]
    InvalidAccessToken,
    [EnumMember(Value = "INVALID_PASSWORD")]
    InvalidPassword,
}